### ISSUE TITLE
Throw an error if passed-in db is deref-able

### ISSUE THREAD

**Issue by sgrove** [tonsky/datascript#101]
Would you accept a patch that would throw an error via a pre-condition (so it can be removed in production builds with no perf hit) if a user passes in a db/conn that supports `deref` to `d/q`, `d/entity`, or `d/pull`? It would help new users in particular when they forget to deref the db, and end up with an error saying `Uncaught Error: [object Object] is not ISeqable`

**Comment by tonsky** [comment]
Sounds like a good idea. Please use `datascript.core/db?` for the check
