### ISSUE TITLE
Entity with lookup ref

### ISSUE THREAD

**Issue by MattParker89** [tonsky/datascript#110]
I'm trying to get an entity using a lookup ref but I'm getting weird results. I'm probably missing something here.

```
=>(d/entity @conn 245)
{:db/id 245}

=>(d/entity @conn [:item/id (:item/id *1)])
{:db/id 245}

=>(:item/id *1)
#uuid "27c1f4e4-ce58-4a46-9c36-d9bd1f573309"

=>(d/entity @conn [:item/id #uuid "27c1f4e4-ce58-4a46-9c36-d9bd1f573309"])
nil

=>(d/entity @conn [:item/id nil])
{:db/id 245}
```
Those last two have me confused. When I put in the value myself why would it return nil? Why would a nil :item/id return anything?

My schema has :item/id as {:db/unique :db.unique/identity}.

**Comment by tonsky** [comment]
That’s interesting! Is it ClojureScript? I once got very annoying bug with transit/uuids where transit introduced their own UUID class and regular UUIDs were not comparable with UUIDs read from transit.

Can you run `(compare (:item/id *1) #uuid "27c1f4e4-ce58-4a46-9c36-d9bd1f573309")`, also `(= .. ..)` and probably `(type ..)` for both?

`(d/entity @conn [:item/id nil])` is hilarious too. Do you, by any change, store any nulls in your DB?

Can you reliably reproduce it? Can I have a test case? Also please report versions of everything (clojure, DS, cljs, compilation mode)

Thanks!

**Comment by MattParker89** [comment]
The transit issue was it! When I did (d/entity @conn [:item/id (transit/uuid "27c1f4e4-ce58-4a46-9c36-d9bd1f573309")]) it worked.

I'll try to recreate the nil issue in a project and share it with you. I don't have nulls in my DB. 

Deps
```
[org.clojure/clojure "1.7.0"]
[org.clojure/clojurescript "0.0-3308"]
[datascript "0.11.6"]
```
This is in dev. No optimizations. I'm also using fig wheel.

Thanks for the help and this project!

**Comment by tonsky** [comment]
Here’s where it all started
https://github.com/cognitect/transit-cljs/pull/10

You’re happy we’ve found it that quick :) I was pulling out my hair when I
first encountered it. Since then, I always do

```clj
      (transit/read
        (transit/reader :json
                      { :handlers { "u" uuid } }) s)
```

(make transit read `cljs.core/uuid` from #uuid tag)

**Comment by MattParker89** [comment]
@tonsky Took me a little while to get around to it but here's a project with an example of the nil problem
https://github.com/MattParker89/ds-nil

**Comment by tonsky** [comment]
@MattParker89 do I understand correctly that this issue is resolved when you add `{ :handlers { "u" uuid } }` to the reader?
