### ISSUE TITLE
function expression binding in where clause not working

### ISSUE THREAD

**Issue by sonwh98** [tonsky/datascript#111]
in datomic,
```
 (d/q '[:find ?r :where [(subs "abc123" 0 3) ?r]])
```
returns  #{["abc"]}

but datascript returns an empty set

**Comment by jaen** [comment]
Tak a look at https://github.com/tonsky/datascript#project-status and this part in particular:

> Interface differences:
>  * Custom query functions and aggregates should be passed as source instead of being referenced by symbol (due to lack of resolve in CLJS)

so I just think that's a limitation of how datascript & Clojurescript are written. Not sure if now that cljs is self-hosted this can be worked around or not.

You'd have to do something like
```
(d/q '[:find ?r ?subs :where [(?subs "abc123" 0 3) ?r]] subs)
```
if I recall correctly.

**Comment by sonwh98** [comment]
thank you! it needs an :in 

```
(d/q '[:find ?r :in ?subs :where [(?subs "abc123" 0 3) ?r]] subs)
```

**Comment by tonsky** [comment]
Thanks @jaen for the help! This turns into a nice forum :)

(btw some fns work without `:in`, here is the list https://github.com/tonsky/datascript/blob/0.11.6/src/datascript/query.cljc#L140-L145)

Ok, let’s let this open, as there’s two things that should be changed in DS:

1. subs should be included to built-ins
2. exception should be thrown on unknown function

**Comment by tonsky** [comment]
Added `subs` to built-ins in bcdb222f7b8883aec6e3a5889bf880f31a14ba6e
Exception on unknown built-in will be thrown in ff887c8f69aa3da466f5e25679daf0865c64e4d0
