### ISSUE TITLE
Documentation request: are there any performance problems to using `db-with` over `transact!` ?

### ISSUE THREAD

**Issue by vvvvalvalval** [tonsky/datascript#112]

**Comment by tonsky** [comment]
No. `transact!` uses `db-with` internally.

**Comment by vvvvalvalval** [comment]
Thanks! Maybe I could start a FAQ page in the Wiki for this sort of stuff?

**Comment by tonsky** [comment]
Sure, go ahead: https://github.com/tonsky/datascript/wiki/FAQ
