### ISSUE TITLE
pull api on connection instead of db

### ISSUE THREAD

**Issue by rhacker** [tonsky/datascript#119]
Hi guys, I'm looking for a way to use pull api. The workflow I use now is 
```
(let [conn (d/create-conn schema)
    (d/transact! conn seed))
 ```

Basically I load the fixtures through a map instead of using datoms in the pull api example ( in test suite ). Is there anyway we can get db from conn or creating db from schema and seed my way, because loading atoms is a bit hard to see when working with fixtures.

Thanks !

**Comment by tonsky** [comment]
I’m not sure I understand you right. To get DB from Conn just do `deref` or `@`. It’s the recommended way.

**Comment by rhacker** [comment]
@tonsky That is exactly what I'm talking about. I'm very new to datomic and datascript.

Thanks

**Comment by tonsky** [comment]
Great! Feel free to ask more :)
