### ISSUE TITLE
Making datascript.db/with-datom public?

### ISSUE THREAD

**Issue by aaronc** [tonsky/datascript#121]
For my use case, I am using datascript as a cache for real datoms in datomic and I want to preserve the t value from datomic (instead of letting datascript assign one). I also have no need for having datascript generate tx-reports or any tx fn's, so I can accomplish this easily using `datascript.db/with-datom`. I am currently referencing it as a var `(#'db/with-datom ...)` to get around the fact that it is private.

Would you consider making it public and a semi-official part of the API (specifically for this use case)?

If so, one other small modification is needed to make it work smoothly with datomic which is to change the this `let` binding - https://github.com/tonsky/datascript/blob/master/src/datascript/db.cljc#L804 - to a `with-let`. This is because datomic sometimes sends the retraction datom after the addition datom and this causes a null pointer exception in Datascript. I can work around this fine in my code, but it requires doing a redundant `-find` to look up the datom.

**Comment by tonsky** [comment]
I’m thinking about allowing raw datoms participate in transactions. I do not promise you it’ll be `with-datom`, but it will be something, I think.

> datomic sometimes sends the retraction datom after the addition datom

Can you give more specific example? When Datomic does that, and what exact sequence of datoms causes NPE in DataScript? If you add and then delete the same datom it should work ok.

**Comment by tonsky** [comment]
Ok here’s what I did:

- you can pass datoms to transact!, it will keep transaction number and respect :added attribute (addition/retraction)
- you can pass transaction number to `:db/add` as well: `[:db/add 1 :name "Ivan" 100]`. Yes it means you can mess up transaction numbers, so be prepared to face the consequences
- I changed `let` to `if-let` in `with-datom` so your use-case should work now
- If you still prefer `with-datom` feel free to continue to using it via var dereferencing, I kept it private for now

**Comment by theronic** [comment]
@aaronc I have a similar use-case, primarily wanting to use DataScript as a two-way cache with less impedance mismatch to Datomic so I can query a set of relatively small user-specific data in the browser. Queries spanning many users' data can happen on the server.

Could you show an example of how you are bringing together all these elements, or point me in the right direction? Any pitfalls?
