### ISSUE TITLE
entity with single attribute ":db/id" can only be pulled by wildcard

### ISSUE THREAD

**Issue by ThomasDeutsch** [tonsky/datascript#123]
Very simple case:

For an entity, that only has a :db/id attribute ```{:db/id 1}```

``` (d/pull db [:db/id] 1) ```  will return ```nil```
``` (d/pull db '[*] 1)``` will return ```{:db/id 1}```

Is this a bug?
I think this behavior should be consistent, and the first case should return ```{:db/id 1}```, too.

**Comment by tonsky** [comment]
Entity can’t have only `:db/id` attribute. It can’t even have `:db/id` attribute at all. It’s a special, reserved name to represent entity id for cases when you look at entity in map form. If you remember, all data is stored as tuples `<e, a, v>` where `e` is that :db/id. If you have no attributes, there’ll just be no records about that entity.

Does it help? If you’ve managed to create entity with `:db/id` as an actual attribute, it is a bug: validation should’ve catched that. Please share details.

**Comment by ThomasDeutsch** [comment]
Thanks for the help.

It is easy to create such an entity: 
```clj
 (d/transact! conn [{:db/id -1}])   ;; simple as that.
```

Why would i do that?
In my app, a placement can contain multiple bookings.
When i create a placement, a new booking will be added to this placement, too.
```clj
(defn new-placement []
    (let [new-booking {:db/id -2}
          new-placement {:db/id -1
                 :placement/show.booking-form? true
                 :placement/bookings [-2]
                 :placement/selected-booking -2}]
      (d/transact! conn [new-booking
                         new-placement
                         [:db/add 0 :scheduler/selected-placement -1]])))
```
It will be easy for me to find an attribute i can fill with some default data - but using only {:db/id ..} was convenient.

**Comment by tonsky** [comment]
Sorry, but `(d/transact! conn [{:db/id -1}])` doesn’t creates a thing. Try printing `(d/datoms @conn)`, or `(:tx-data (d/transact! conn [{:db/id -1}]))`.

What you see from `d/datoms` is how data is actually stored. Think about it in terms of how things are implemented: if you’re not storing an attribute for the entity, there’s not place for entity id as well. Entity only exists if you’re saying something about it.
