### ISSUE TITLE
:db.fn/cas should be able to use nil for old value

### ISSUE THREAD

**Issue by petterik** [tonsky/datascript#126]
Transactions fail when performing db.fn/cas on an entity which does not have an old value for the compared attribute:
```clj
(def conn (d/create-conn))
(d/transact! conn [[:db/add 1 :weight 200]])
 ;; works as expected:
(d/transact! conn [[:db.fn/cas 1 :weight 200 300]])
;; crashes with message "Cannot store nil as a value at [:db.fn/cas 1 :foo nil :bar]":
(d/transact! conn [[:db.fn/cas 1 :foo nil :bar]]) 
```
Expected entity 1: `{:weight 300 :foo :bar}`

From Datomic docs (http://docs.datomic.com/transactions.html):
> You can use nil for the old value to specify that the new value should be asserted only if no value currently exists.

**Comment by jdf-id-au** [comment]
Just to spell it out, the reverse of the last operation above is:

`(d/transact! conn [[:db/retract 1 :foo :bar]])`

(I was trying to work out why `(d/transact! conn [[:db.fn/cas 1 :foo :bar nil])` felt wrong!)
