### ISSUE TITLE
UUID is not seqable

### ISSUE THREAD

**Issue by lorddoig** [tonsky/datascript#128]
```clojure
(d/transact! conn [{:db/id -1
                    :name name
                    :id <some-cljs.core/UUID>}])
```

This throws with the string representation of the UUID "is not seqable".  Casting to string first works fine.

Am I misusing/abusing datascript?  Have I missed something?  Or is this a bug?  Other issues suggest UUIDs are supported.

**Comment by tonsky** [comment]
Can I see a schema?

**Comment by tonsky** [comment]
Cannot do anything unless I have more details from you
