### ISSUE TITLE
Relationship to Datomic

### ISSUE THREAD

**Issue by ccorcos** [tonsky/datascript#129]
> DataScript is built totally from scratch and is not related by any means to the popular Clojure database Datomic

They seem peculiarly similar -- are they really not meant to work together?

**Comment by tonsky** [comment]
It is modelled after Datomic, all the APIs, in some sense, parts of the
architecture. They work together rather well. But it’s completely
independent project, Cognitect wanted this to be stated clear, so no
confusion.

**Comment by ccorcos** [comment]
Interesting. Well Datomic is closed source I'm just realizing. It would be sweet if this were just a seamless client side cache / pub/sub for datomic... This isn't meant to be a fully fledged database is it?

**Comment by tonsky** [comment]
No. There’re some project aiming to seamless sync between Datomic and
DataScript. E.g. http://github.com/sgrove/dato

**Comment by ccorcos** [comment]
awesome! Just curious, what are types of queries or systems that datomic is necessarily not so good at?

**Comment by tonsky** [comment]
Frequent in-place updates, I think.

**Comment by ccorcos** [comment]
well the whole point is that its not in-place... lol
