### ISSUE TITLE
not= not working as expected

### ISSUE THREAD

**Issue by hlship** [tonsky/datascript#134]
I'm trying to solve some NPR sunday puzzles with Datascript.

I have loaded a bunch of words to form a database.

```
(def schema {})

(defonce conn (d/create-conn schema))

(defn annagram
  "Returns the word with the characters sorted into ascending order."
  [word]
  (->> word
       sort
       (apply str)))

(defn transact-word
  [^String word]
  {:word word
   :length (.length word)
   :annagram (annagram word)})

(defn add-words
  [conn words]
  (d/transact! conn (map transact-word words)))

(add-words conn ["cat" "dog" "god" "flea"])
```

Now I execute a query:

```
(d/q '[:find ?word-1 ?word-1.word ?word-2 ?word-2.word
         :where
         [(not= ?word-1 ?word-2)]
         [?word-1 :length ?length]
         [(= 3 ?length)]
         [?word-2 :length ?length]
         [?word-1 :annagram ?ann]
         [?word-2 :annagram ?ann]
         [?word-1 :word ?word-1.word]
         [?word-2 :word ?word-2.word]]
       @conn)
=>
#{[1 "cat" 1 "cat"]
  [3 "god" 2 "dog"]
  [2 "dog" 3 "god"]
  [3 "god" 3 "god"]
  [2 "dog" 2 "dog"]}
```

So ... despite me explicitly saying _don't match yourself_ ... it matches itself.  I'm *very* new to this style of coding (but fun!), but I'm pretty sure I should not see `[1 "cat" 1 "cat"]` etc. in the output.

I hate adding issues to discuss this; is there an IRC or Slack where we can discuss?

**Comment by hlship** [comment]
Datascript 0.1.13

**Comment by tonsky** [comment]
The :where clauses are analyzed in order they’re specified, there’s no
analysis or reordering in DS. Just move not= clause later when both ?word-1
and ?word-2 are already defined, and it should work. Also you can get rid
of (= 3 ?length):

(d/q '[:find ?word-1 ?word-1.word ?word-2 ?word-2.word
       :where
         [?word-1 :length 3]
         [?word-2 :length 3]
         [(not= ?word-1 ?word-2)]
         [?word-1 :annagram ?ann]
         [?word-2 :annagram ?ann]
         [?word-1 :word ?word-1.word]
         [?word-2 :word ?word-2.word]]
       @conn)

**Comment by hlship** [comment]
That worked, thanks. Still pinning down when a symbol is bound or unbound, I guess.
