### ISSUE TITLE
Dynamically bound subquery pattern in a pull expression fails using Datomic syntax

### ISSUE THREAD

**Issue by thos37** [tonsky/datascript#136]
Datomic supports binding a `subquery` pattern in a query's pull function:
```clojure
(d/q '[:find [(pull ?e subquery) ...] 
       :in $ ?a subquery 
       :where [?e ?a]] @conn join-key [(hash-map join-key query)])
```
This syntax fails in Datascript with:
`#error {:message "Cannot parse pull expression, expect ['pull' src-var? variable (constant | variable)]", :data {:error :parser/find, :fragment (pull ?e subquery)}}`

This does however work using regular variable binding syntax `?subquery` even though this fails on Datomic:
```clojure
(d/q '[:find [(pull ?e ?subquery) ...] 
       :in $ ?a ?subquery
       :where [?e ?a]] @conn join-key [(hash-map join-key query)])
```

That said, I think Datascript's syntax is more intuitive but is just different than the [Datomic docs](http://docs.datomic.com/query.html)

**Comment by tonsky** [comment]
Thanks Thomas! So tired here fixing all the Datomic inconsistencies :)
