### ISSUE TITLE
Recursive pull patterns?

### ISSUE THREAD

**Issue by metasoarous** [tonsky/datascript#149]
It would be nice to be able to use `...` for recursion in pull patterns, as we can with Datomic `pull`. When I try this in DataScript it complains that `...` is not seqable. At the very least a doc update would be nice (which I'm happy to submit).

**Comment by hden** [comment]
Works pretty well for me, see [this gist](https://gist.github.com/hden/a371c83dc724e092bc02108f06580fd0). Do you have a minimum sample for your code?

**Comment by metasoarous** [comment]
Hmm... ok. Sorry for the noise then. It's possible this was actually a posh bug (I'll chat with @mpdairy about this). I've already rewritten the code, but if I revisit and reproduce the error, I'll try to narrow things down and reopen if I find an edge case in DataScript.
