### ISSUE TITLE
Support `:db.type/keyword` in schema

### ISSUE THREAD

**Issue by thedavidmeister** [tonsky/datascript#152]
I have an attribute that looks like this in my schema:

```
:foo/name {:db/unique :db.unique/identity
                  :db/valueType   :db.type/keyword}
```

I'm adding to it from quite a few different places in my code, but it's always a keyword. I was hoping to not have to write `:pre` conditions to enforce the keyword-ness, and let the enforcing happen at the db level, but the above schema does not work.

I get this error:

`db.cljc:536Uncaught #error {:message "Bad attribute specification for {:foo/name {:db/valueType :db.type/keyword}}, expected one of #{:db.type/ref}", :data {:error :schema/validation, :attribute :foo/name, :key :db/valueType, :value :db.type/keyword}}`

**Comment by tonsky** [comment]
The only value type supported ATM is :db.type/ref. For anything else, just
don’t specify :db/valueType

**Comment by tonsky** [comment]
I mean, values of all types are supported, just don’t specify type of them
in a schema

**Comment by thedavidmeister** [comment]
@tonsky oh, is there a particular reason for that? it would be really helpful to support this.

**Comment by thedavidmeister** [comment]
@tonsky what would actually be involved in adding a few extra types? is it more than just doing a type error on an attempted `transact!`?

**Comment by tonsky** [comment]
There’re few complications: see my comments https://github.com/tonsky/datascript/pull/107

**Comment by thedavidmeister** [comment]
@tonsky well no, not complications, you just said in #107 that you're looking for a use case.

If not schemas directly ported from datomic, some kind of validation at the db level would be great!

My use case is that:
- I want to write some nicely named utility functions `set-foo!`, `set-bar!`, etc...
- Those functions do some transactions under the hood
- The functions are all working with the same type of data and the same bits of datoms in the db
- I don't really want to have to sprinkle the same validation calls through all my utility functions, I'd rather just have the db tell me when I screw up

**Comment by pangloss** [comment]
Hi David, what you are describing can easily be done without any change to
datascript using just a simple macro. Here is a quick example I threw
together just to get you started.

(def global-conn (d/create-conn {}))

(defmacro property-setter [validate-fn k]
  `(let [k# ~k]

     (defn ~(symbol (str "set-" (name k))) [entity# new-value#]
       (when-not (~validate-fn new-value#)
         (throw (ex-info "invalid" {:property k# :value new-value#})))
       (d/transact global-conn entity# [[(:db/id entity#) k#
new-value#]]))))

(property-setter keyword? :my-keyword)
