### ISSUE TITLE
:db.unique/identity doesn't merge with JS API

### ISSUE THREAD

**Issue by terinjokes** [tonsky/datascript#153]
Marking a schema as containing a unique identity doesn't merge the entities with the JS API. I've created a reproducible test case at https://gist.github.com/terinjokes/a5003ab475a6fb5eddaa.

**Comment by typeetfunc** [comment]
@terinjokes 
https://tonicdev.com/parabellum06-94/56f396a75d25f21100563b7d
In schema [all string transformed to keyword](https://github.com/tonsky/datascript/blob/master/src/datascript/js.cljs#L17).
However, [string in entities are not transformed](https://github.com/tonsky/datascript/blob/master/src/datascript/js.cljs#L31).
`":my/tid" !== :my/tid`
Just do not use keyword-like string as attributes.

**Comment by terinjokes** [comment]
@typeetfunc thanks, I'll avoid using keywords there.

**Comment by tonsky** [comment]
Just pushed 0.15.1
