### ISSUE TITLE
How to drop database?

### ISSUE THREAD

**Issue by sandric** [tonsky/datascript#154]
Sorry for maybe a dumb question - I'm new to datalog. My particular interest is in complete and fast destroy of whole database - for now I iteratively delete all keys but thats too long. I need that because of lein figwheel not reloading somehow datascript database - after each change to project its repopulates with fixtures, and the same is with compiled js imported into rails app - doe to turbolinks I guess. thx.

**Comment by tonsky** [comment]
Database is nothing more but a pointer. Just forget about old one and
create a new one.

If you want to keep a connection, but replace a DB it references, do
(d/reset-conn! conn (d/empty-db schema))
