### ISSUE TITLE
Validate Schema valueType is too restrictive?

### ISSUE THREAD

**Issue by taylorSando** [tonsky/datascript#159]
Would it be possible to remove the valueType validation?  I wouldn't mind being able to define some other valueTypes.
https://github.com/tonsky/datascript/blob/a8da9eb9ae61ad31f68a51493ba03b3782d51602/src/datascript/db.cljc#L552

**Comment by tonsky** [comment]
I don’t want stuff in schema not meaning anything. And I can’t figure out how to add types and enforce their meaning, at least not now. See prior history in #107 and #152
