### ISSUE TITLE
ability to put metadata on a datom

### ISSUE THREAD

**Issue by thedavidmeister** [tonsky/datascript#160]
I'm looking to put some information in the metadata on datoms to make it easier to co-ordinate them with my (non-datomic) persistence backend. I want to play around with things like `squuid` and timestamps, but am currently not sure exactly where to put this information.

Datoms currently do not implement `IMeta` or `IMetaWith` which is what I think they'd need to make this possible.

**Comment by tonsky** [comment]
Hi,

metadata would mean an additional field to store, additional copy operation to do and additional checks when working with Datoms. Because datoms are so low-level and on a hot path all the time, it would be too expensive to have “just in case”.

Try using attributes instead
