### ISSUE TITLE
`:db/ident` support

### ISSUE THREAD

**Issue by gfZeng** [tonsky/datascript#162]
Does DataScript think support `:db/ident`?

**Comment by tonsky** [comment]
Not exactly. Last time I looked at them, they were source of a great
confusion (e.g. entity api would return idents but pull api will return
ids, can’t use them in queries, etc). Much easier to use keywords directly.
Also there’s a certain performance hit associated with idents.

But you can always create :db/ident attribute in schema, mark it as
:db.unique/identity and use lookup refs to access entities you need
reference via keywords

**Comment by gfZeng** [comment]
I think the enumerators use `db/ident` better than `keyword`.
well, the `db/ident` support additional attribute,
and also can loop up entity via `keyword`
