### ISSUE TITLE
Using a lookup ref complains that it wants a db.unique/identity attribute

### ISSUE THREAD

**Issue by robert-stuttaford** [tonsky/datascript#171]
Doesn't accept :db.unique/value.

**Comment by metasoarous** [comment]
I think this is in line with Datomic's behavior (http://blog.datomic.com/2014/02/datomic-lookup-refs.html).

**Comment by tonsky** [comment]
Modern Datomic let you use any unique value in lookup refs. Maybe it wasn’t the case when they were first introduced, or I haven’t checked that properly. Anyways, fixed now

**Comment by metasoarous** [comment]
I stand corrected; Good to know.
