### ISSUE TITLE
More specific end condition for transact-tx-data

### ISSUE THREAD

**Issue by marcolisi** [tonsky/datascript#184]
First I would like to say: amazing work! Thank you.

I would like to know what you would think of making the end condition for the function `transact-tx-data` more specific?

The reason being: transactions are being created dynamically and sometimes an entity in the middle of the list is `nil`, which is normal, and this creates the effect of not processing the entities following the `nil`. This little detail took me a while to debug and understand why some of the entities were not being created.

Instead of just `(nil? entity)` can it be something like `(and (nil? entity) (empty? entities))`?

Although, this change would necessitate the handling of a new condition which should just `recur`, such as:

``` clojure
(and (nil? entity) (not (empty? entities)))
 (recur report 
        entities)
```

Thanks again! Your ways of thinking and contributions are much appreciated.

**Comment by marcolisi** [comment]
Thanks!

Done in release 0.16.3

**Comment by tonsky** [comment]
Oh, great! Seems like I accidentally fixed your issue :) Pretty bad one, took me couple of hours figuring of debugging before I understood what’s going on
