### ISSUE TITLE
Avoid `declare` use in cljs for function with only one arity

### ISSUE THREAD

**Issue by rauhs** [tonsky/datascript#197]
Affects: `datascript.db`

The clojurescript compiler, when seeing a `declare` won't know what arity the function will be. This means it'll generate code like this for the Datom type:

```clojure
  return $datascript$db$val_at_datom$$.$cljs$core$IFn$_invoke$arity$3$
  ? $datascript$db$val_at_datom$$.$cljs$core$IFn$_invoke$arity$3$(this, $k$$288$$, null)
  : $datascript$db$val_at_datom$$.call(null, this, $k$$288$$, null);
```

The special `$arity$3` function will never be genrated, since `val-dat-atom` is only a one arity function. So this construct will *always* use `.call(null...)` to call the function. This however isn't optimal and is slower.

So best is to completely avoid `declare` with clojurescript in critical code.

An option is to move the `deftype` up, define the functions, and then use `extend-type`.

**Comment by tonsky** [comment]
CLJS issue http://dev.clojure.org/jira/browse/CLJS-1871
