### ISSUE TITLE
Error when aliasing and pulling in the same query

### ISSUE THREAD

**Issue by EugenDueck** [tonsky/datascript#201]
This works

```
(ds/q '[:find (pull ?e [*]) :in $ :where [$ ?e ?a ?v]] @ds-db)
```

This does not
```
(ds/q '[:find (pull ?e [*]) :in $x :where [$x ?e ?a ?v]] @ds-db)

AssertionError Assert failed: (db? db)  datascript.db/entid (db.cljc:726)
```

These all work as well
```
(ds/q '[:find (pull ?e [*]) :where [?e ?a ?v]] @ds-db)
(ds/q '[:find ?e ?a ?v :in $ :where [$ ?e ?a ?v]] @ds-db)
(ds/q '[:find ?e ?a ?v :in $x :where [$x ?e ?a ?v]] @ds-db)
```

So it seems to have something to do with pulls.

**Comment by tonsky** [comment]
Try `(ds/q '[:find (pull $x ?e [*]) :in $x :where [$x ?e ?a ?v]] @ds-db)`

**Comment by EugenDueck** [comment]
I see. I guess that makes sense. `pull` has to pull from some db, whereas the find clause can just return the bound variables.

**Comment by EugenDueck** [comment]
Otoh, `pull` could internally be provided with the input that the entity id in question comes from. That's how datomic does it, where [the grammar doesn't even allow](http://docs.datomic.com/query.html#outline-container-4-2) specifying the input in a pull expression.

The following works in datomic:
```
(dt/q '[:find (pull ?e [*]) (pull ?f [*]) :in $a $b :where [$a ?e :order/id] [$b ?f :account/user-name]] (db dt-conn) (db dt-conn))
```
Not sure though if you datascript strives to be as close to datomic's specification as possible, so will leave this issue closed, as it can be made to work.
