### ISSUE TITLE
datascript-pseudo-names-bug

### ISSUE THREAD

**Issue by tonsky** [tonsky/datascript#206]
I have an app using Datascript that works in dev mode but when I switch advanced compilation I’m getting errors from Datascript, like `Lookup ref attribute should be marked as :db/unique: [:state/part :ui]` even though I have that attribute set as unique in my schema.

Is it common for users to run into issues like this with advanced compilation, or is that suprising?

it doesn’t look like simply switching to advanced compilation is the problem. I’ll keep looking

I found the culprit! Setting the CLJS compiler option `:pseudo-names` to true with advanced compilation throws crazy datascript errors. That sounds pretty crazy, but I’ve found it to be true.

Without `:pseudo-names`
```
(db/-attrs-by db :db/unique) => #{:db/uuid :state/part}
```
With `:pseudo-names`
```
(db/-attrs-by db :db/unique) => #{{:db.unique :db.unique/identity}}
```

https://github.com/AdamFrey/datascript-pseudo-names-bug

**Comment by thedavidmeister** [comment]
I'm seeing this issue sporadically. Sometimes (on the same codebase) pseduo names will break and sometimes they work. No idea what triggers the breakage.

**Comment by tonsky** [comment]
What version of cljs are you on?

**Comment by thedavidmeister** [comment]
`1.9.229`

**Comment by tonsky** [comment]
So there was some compilation/name munglig issue on some versions of the compiler (can’t say I remember what they were, maybe something different.) They do disappeared when I upgraded to 1.9.494. Maybe be give it a go?

**Comment by thedavidmeister** [comment]
i upgraded to `1.9.473` and it got *worse*.
Started seeing `"Lookup ref attribute should be marked as :db/unique: [:project/id nil]"` with pseudo names turned on.
I'll try a higher version of cljs.

**Comment by thedavidmeister** [comment]
i can't upgrade any further until https://github.com/google/closure-compiler/issues/2336 lands

**Comment by tonsky** [comment]
Seems like 494 fixed it. I can reliable reproduce it on 1.9.473 and 1.9.293 on both DataScript repo and @AdamFrey repo. In both cases 494 works flawlessly

**Comment by thedavidmeister** [comment]
kk, i just successfully moved to `1.9.521` for cljs, which means google must have pushed a new release for the compiler.

i'll let you know if i ever see this error again, thanks!
