### ISSUE TITLE
Maximum call stack size exceeded on 1.9.473

### ISSUE THREAD

**Issue by tonsky** [tonsky/datascript#210]
@bbss in Slack:

> Hmm strange. I'm getting a maximum call stack size exceeded in a simple attribute query, this test for example errors: https://github.com/tonsky/datascript/blob/master/test/datascript/test/query.cljc#L23
> Hmm, it doesn't seem to be an issue with "1.9.293" but just with latest "1.9.473".

**Comment by wambat** [comment]
Same issue, looks like it cycles in recursion here 
https://github.com/tonsky/datascript/blob/master/src/datascript/parser.cljc#L55

**Comment by anmonteiro** [comment]
FWIW, `cljs.core/seqable?` changed in the latest release of ClojureScript. See https://github.com/clojure/clojurescript/commit/101d7d9e03e90518e6769781dd33fbe6387d2d44

**Comment by seantempesta** [comment]
Are you planning to release this?  I just started using 15.5 with Clojurescript 1.9.494 and ran into this issue.

**Comment by claj** [comment]
Thanks a ton for fixing this!

**Comment by tonsky** [comment]
@seantempesta just released 0.16.0

**Comment by seantempesta** [comment]
Thank you!
