### ISSUE TITLE
Predicate for checking if something exists in a set

### ISSUE THREAD

**Issue by jlo1** [tonsky/datascript#211]
Ideally, the `built-ins` here https://github.com/tonsky/datascript/blob/0.15.5/src/datascript/query.cljc#L150 could support `contains?`. Is there a way to workaround this with other built in queries atm?

**Comment by tonsky** [comment]
Just tried, and it works fine for me:

```
(d/q '[:find ?val 
       :in $ ?contains-fn
       :where [_ :attr ?val]
              [(?contains-fn #{"s1" "s2" "s3"} ?val)]]
     (-> (d/empty-db)
         (d/db-with [[:db/add 1 :attr "x"]
                      [:db/add 2 :attr "s1"]
                      [:db/add 3 :attr "y"]
                      [:db/add 4 :attr "s2"]]))
      contains?)
```

But I’ll accept a PR that adds `contains?` if you fire one
