### ISSUE TITLE
Input parameter used within lookup ref results in ClassCastException

### ISSUE THREAD

**Issue by markaddleman** [tonsky/datascript#213]
`(let [db (d/empty-db {:k {:db/unique :db.unique/identity}})]
  (d/q '[:find ?v
         :in $ ?k
         :where
         [[:k ?k] :v ?v]]
    (d/db-with db [[:db/add -1 :k "key"]
                   [:db/add -1 :v "value"]])
    "key"))`

results in CastCastException:
`#error{:cause "clojure.lang.Symbol cannot be cast to java.lang.String",
       :via [{:type java.lang.ClassCastException,
              :message "clojure.lang.Symbol cannot be cast to java.lang.String",
              :at [java.lang.String compareTo "String.java" 111]}],
       :trace [[java.lang.String compareTo "String.java" 111]
               [clojure.lang.Util compare "Util.java" 153]
               [datascript.db$cmp_val invokeStatic "db.cljc" 293]
               [datascript.db$cmp_val invoke "db.cljc" 291]
               [datascript.db$cmp_datoms_avet invokeStatic "db.cljc" 316]
               [datascript.db$cmp_datoms_avet invoke "db.cljc" 313]
               [datascript.btset$binary_search_l invokeStatic "btset.cljc" 72]
               [datascript.btset$binary_search_l invokePrim "btset.cljc" -1]
               [datascript.btset$_seek invokeStatic "btset.cljc" 951]
               [datascript.btset$_seek invoke "btset.cljc" 941]
               [datascript.btset$_slice invokeStatic "btset.cljc" 979]
               [datascript.btset$_slice invoke "btset.cljc" 978]
               [datascript.btset$slice invokeStatic "btset.cljc" 990]
               [datascript.btset$slice invoke "btset.cljc" 985]
               [datascript.btset$slice invokeStatic "btset.cljc" 988]
               [datascript.btset$slice invoke "btset.cljc" 985]
               [datascript.db.DB _datoms "db.cljc" 373]
               [datascript.db$entid invokeStatic "db.cljc" 742]
               [datascript.db$entid invoke "db.cljc" 726]
               [datascript.db$entid_strict invokeStatic "db.cljc" 750]
               [datascript.db$entid_strict invoke "db.cljc" 749]
               [datascript.query$resolve_pattern_lookup_refs invokeStatic "query.cljc" 599]
               [datascript.query$resolve_pattern_lookup_refs invoke "query.cljc" 595]
               [datascript.query$_resolve_clause invokeStatic "query.cljc" 627]
               [datascript.query$_resolve_clause invoke "query.cljc" 616]
               [datascript.query$resolve_clause invokeStatic "query.cljc" 642]
               [datascript.query$resolve_clause invoke "query.cljc" 634]
               [clojure.lang.PersistentVector reduce "PersistentVector.java" 341]
               [clojure.core$reduce invokeStatic "core.clj" 6703]
               [clojure.core$reduce invoke "core.clj" 6686]
               [datascript.query$_q invokeStatic "query.cljc" 645]
               [datascript.query$_q invoke "query.cljc" 644]
               [datascript.query$q invokeStatic "query.cljc" 769]
               [datascript.query$q doInvoke "query.cljc" 754]
               [clojure.lang.RestFn invoke "RestFn.java" 439]
               [datascript_bug$eval65971 invokeStatic "form-init5167428913138369599.clj" 2]
               [datascript_bug$eval65971 invoke "form-init5167428913138369599.clj" 1]
               [clojure.lang.Compiler eval "Compiler.java" 6978]
               [clojure.lang.Compiler eval "Compiler.java" 6941]
               [clojure.core$eval invokeStatic "core.clj" 3187]
               [clojure.core$eval invoke "core.clj" 3183]
               [clojure.main$repl$read_eval_print__9983$fn__9986 invoke "main.clj" 242]
               [clojure.main$repl$read_eval_print__9983 invoke "main.clj" 242]
               [clojure.main$repl$fn__9992 invoke "main.clj" 260]
               [clojure.main$repl invokeStatic "main.clj" 260]
               [clojure.main$repl doInvoke "main.clj" 176]
               [clojure.lang.RestFn invoke "RestFn.java" 1523]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__34095 invoke "interruptible_eval.clj" 87]
               [clojure.lang.AFn applyToHelper "AFn.java" 152]
               [clojure.lang.AFn applyTo "AFn.java" 144]
               [clojure.core$apply invokeStatic "core.clj" 657]
               [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1963]
               [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1963]
               [clojure.lang.RestFn invoke "RestFn.java" 425]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 85]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
               [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__34140$fn__34143
                invoke
                "interruptible_eval.clj"
                222]
               [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__34135
                invoke
                "interruptible_eval.clj"
                190]
               [clojure.lang.AFn run "AFn.java" 22]
               [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
               [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
               [java.lang.Thread run "Thread.java" 745]]}
`

**Comment by tonsky** [comment]
Should’ve been

```clj
(let [db (d/empty-db {:k {:db/unique :db.unique/identity}})]
  (d/q '[:find ?v
         :in $ ?k
         :where [?e :k ?k] 
                [?e :v ?v]]
    (d/db-with db 
      [[:db/add -1 :k "key"]
       [:db/add -1 :v "value"]]) "key"))
```
