### ISSUE TITLE
Optimize -attrs-by in DB

### ISSUE THREAD

**Issue by rauhs** [tonsky/datascript#222]
See: https://dev.clojure.org/jira/browse/CLJS-2041

This mean's the `get`ing of the attributes is going through a slow `.call` which again does a slow `switch-case` and only then gets to the actual `get` of the `rschema` map.

Should be: `(get (.-rschema db) property)`

**Comment by rauhs** [comment]
Obsolete. I fixed that in the CLJS compiler.

**Comment by tonsky** [comment]
best way to fix :) Thanks!
