### ISSUE TITLE
Add "keyword" to "built-ins"

### ISSUE THREAD

**Issue by marcolisi** [tonsky/datascript#231]
Would it be possible to add `keyword` to the list of `built-ins`, as I am getting in some circumstances the following error: `Unknown function 'keyword in [(keyword ?v-s?) ?v] {:error :query/where, :form [(keyword ?v-s?) ?v], :var keyword}`

I am uncertain as to why this same query sometimes gives the error and other times it does not.

Query:
```clojure
'[:find ?v
 :in $ [?t ?acr ?a ?av1 ?av2 ?ai]
 :where
   [?e ?acr ?a]
   [(name ?t) ?t-s]
   [?e ?av1 ?t-s]
   [?e ?av2 ?v-s]
   [(keyword ?v-s?) ?v]
   [?e2 ?ai ?v]]
```

Thank you! Your work is greatly, very greatly, appreciated!

**Comment by tonsky** [comment]
Sure, easy to add. As for errors, it might not throw if at that point there’re no matching tuples so there’s nothing to apply it t

**Comment by marcolisi** [comment]
Thank you! 

And thank you for the explanation, makes sense to me now.  :)
