### ISSUE TITLE
Advanced compilation warning

### ISSUE THREAD

**Issue by Odinodin** [tonsky/datascript#233]
When compiling a project using ClojureScript 1.9.660 and Datascript 0.16.1 the following warning is emitted: 

`WARNING: .../resources/public/js/compiled/out/min/datascript/parser.js:7241: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return (!((other21477 == null))) && ((this21476__$1.constructor === other21477.constructor)) && (cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(this21476__$1.find,other21477.find)) && (cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(this21476__$1.with,other21477.with)) && (cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(this21476__$1.in,other21477.in)) && (cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(this21476__$1.where,other21477.where)) && (cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(this21476__$1.__extmap,other21477.__extmap));`

As far as I can tell, the problem is the use of reserved words like `with` and `in`

**Comment by tonsky** [comment]
Thanks, I’ve seen it too but haven’t looked into it yet. I’ll take a look

**Comment by Odinodin** [comment]
As a workaround I've added `:language_in ecmascript5` as a cljs compiler option to my project.

**Comment by tonsky** [comment]
It’s caused by defrecord in parser https://dev.clojure.org/jira/browse/CLJS-2237
