### ISSUE TITLE
Is there a work-around for negation?

### ISSUE THREAD

**Issue by jconti** [tonsky/datascript#238]
To read the [Datomic description of negation](http://docs.datomic.com/query.html#not-caluses) leads me to suspect that there is a way to write (a more complicated) query without `not` that would have the same behavior as `not` by using sub-queries.  Am I mistaken?

**Comment by tonsky** [comment]
I’m not aware of any. Maybe you can use custom-built predicates for that
though

**Comment by bahulneel** [comment]
This also works:

```clojure
(defn not-join-pred
  [db join vars where]
  (let [vals+ (d/q {:find vars
                    :in ['$ [vars '...]]
                    :where where}
                   db
                   [join])]
    (nil? (seq vals+))))

(println
  (d/q '{:find [?a ?b]
         :in [$ ?not-join ?not-expr]
         :where
         [[?e :a ?a]
          [?e :b ?b]
          [(vector ?e) ?join]
          [(?not-join $ ?join [?e] [[?e :c true]])]]}
       (d/db conn)
       not-join-pred))
```

**Comment by bahulneel** [comment]
Here's or-join for completeness:

```clojure

(defn or-join-pred
  [db join vars wheres]
  (let [vals (map #(d/q {:find vars
                         :in ['$ [vars '...]]
                         :where %}
                        db
                        [join])
                  wheres)]
    (first (remove nil? (map seq vals)))))

(println
  (d/q '{:find [?a ?b]
         :in [$ ?or-join]
         :where
               [[?e :a ?a]
                [?e :b ?b]
                [(vector ?e ?b) ?join]
                [(?or-join $ ?join [?e ?b] [[[(even? ?b)]]
                                            [[?e :c true]]])]]}
       (d/db conn)
       or-join-pred))
```

**Comment by jconti** [comment]
This is clever.  I like that I can take ad-hoc solutions out of my code +1, but a little disappointed that a fair amount of the declarative quality of the query is lost with what ends up being a hack on the where syntax.

@bahulneel Thank you!

**Comment by bahulneel** [comment]
@jconti thanks for your comments, I was beginning to think that no one had noticed this? I'd be interested to see how you've used rules to wrap some of the complexity.

P.S. I figured out the implementation by reading the Datomic docs on the subject.

**Comment by tonsky** [comment]
Implemented not/or/not-join/or-join in 0.17.1. Enjoy!

**Comment by jconti** [comment]
Wow super big thanks to @tonsky and @bahulneel .  I have received so much utility from this project and the contributions you made to this case.  Hopefully I will be able to get some support for the continued health of the project around here.  Really amazing work!

**Comment by bahulneel** [comment]
Excellent work, thanks @tonsky!
