### ISSUE TITLE
Consider ahead of time compilation for maven/clojars artifact

### ISSUE THREAD

**Issue by andrerichards** [tonsky/datascript#241]
Firstly, thanks for a wonderful library.

We use DataScript from Java, and have written a wrapper ([jdatascript](https://github.com/andrerichards/jdatascript)) to make it more idiomatic to access from Java. 

Would you consider using the `:aot` setting when creating the datascript artifact for maven/clojars, as this would make it straightforward to add  jdatascript (and in turn datascript) to a Java maven project, without requiring the developer to add building Clojure files to their pipeline.

I have tested locally by adding the following line to the DataScript `project.clj` and doing `lein jar` and `lein install`, and it worked perfectly:

`:aot [datascript.db]`

Happy to open a pull request, if you prefer.

Thanks for considering.

PS if you would prefer to not add this to the project - is it OK if we create fork of DataScript with this enabled, and distribute on Maven/Clojars as datascript-aot, or any description you want.

Also, if you want to read the [Rationale](https://github.com/andrerichards/jdatascript#rationale) on the jdatascript page, we would welcome any changes you want us to make (e.g. the description of DataScript usage)

**Comment by tonsky** [comment]
It still needs Java wrappers, right? That means you have to use some intermediate library. Can’t you AOT in there?

Long-term plans are to add Java API to DataScript directly, but I doubt it’ll happen any time soon. Meanwhile feel free to do what works best for you

**Comment by andrerichards** [comment]
> It still needs Java wrappers, right?
Yes

> Can’t you AOT in there?
Have tried to specify AOT in intermediate library (for datascipt.db namespace) but Leiningen does not compile those classes (in the intermediate library's build). Will investigate this option further.

> Long-term plans are to add Java API to DataScript directly, but I doubt it’ll happen any time soon. 
Nice. We are obviously happy to contribute whatever we do. We are following the built-in JavaScript wrapper fairly closely, including porting the JS tests to Java. We are changing method names to be more idiomatic Java - dbWith instead of db_with, etc. Parameter and return types are set to the types declared in Clojure (DB, TxReport) - hence the need for AOT. 
If you have any specific ideas or preferences, we are happy to follow those conventions, if it might save you work later. If you have not thought about it, or is not ready to comment, we'll continue on our merry way :)

**Comment by tonsky** [comment]
I was thinking of copying Datomic API actually. But haven’t look into it at all, so it might be not that good of an idea

**Comment by andrerichards** [comment]
I started off with Datomic API, but it is largely based around Java Interfaces (Connection, Database, Datom, Entity are all interfaces). Currently none of the DataScript records implement those interfaces and I did not want to get into the heart of DataScript too much. 

If you decide to go that route and define + implement the interfaces inside DataScript, it could work well.

It would mean the difference between:
`pull(db, ...)`  
and
`db.pull(...)` 

The last one is certainly more 'object-orienty', but I decided that for our use static methods are more straightforward to implement right now, and are good enough.

**Comment by andrerichards** [comment]
I guess the biggest advantage of copying Datomic API is that users can copy Datomic examples.

I could give the Datomic API a go, and provide you with feedback on any issues I run into, if that would help - even if it is throwaway work.

**Comment by andrerichards** [comment]
I did a very, very minimal Datomic-like API implementation to test the possibility and the impact on DataScript code.

See the comments below these commits:

- [53dd897](https://github.com/andrerichards/datascript/commit/53dd897d85361863bafa72be79ab9ffad2b932c3)
- [e51e856](https://github.com/andrerichards/datascript/commit/e51e856ec8706cd0e339385ca4463a2c58e45747)

In short:

- need to declare some Java interfaces, e.g. `datascript.java.Database`
- implement them, e.g. implement `Database` in `datascript.db.DB`
- in many cases implementation simply requires a call to the corresponding function in `datascript.db`, e.g.
```
(defrecord-updatable DB
   ...
   Database (entid [db entityId] (entid db entityId))
   ...)
```
- in some cases it requires moving the function from `datascript.core` to `datascript.db`, as we cannot call `datascript.core` from `datascript.db`, e.g. `db-with`:
```
(defrecord-updatable DB
   ...
   Database (with  [db tx-data]  (db-with db tx-data))
   ...)
```
- I think `Database.pull` might require biggest such change, as there are a bunch of functions declared in a completely different namespace, and many/most of them might have to be moved to `datascript.db`

 
Would you be OK with doing it like this, or does it interfere with some other things you have in mind (or maybe you have other suggestion)?  

I am quite happy to proceed further along this path, and see if I run into any other issues - but it would be useful to know that you are OK with this, at least in principle.

**If you do not have time to look into this and comment now, it's fine. I understand you might be busy  :)**

**Comment by tonsky** [comment]
@andrerichards if you still need AOT-compiled code it’s deployed under classifier now:

```
[datascript "0.16.9-aot1.9"]
```
