### ISSUE TITLE
Unknown function 're-pattern in [(re-pattern ?matcher) ?regex]

### ISSUE THREAD

**Issue by jenyckee** [tonsky/datascript#243]
I am trying to match against a regex but am getting:

`Unknown function 're-pattern in [(re-pattern ?matcher) ?regex]`

Is there any way to use regular expressions in datascript?

**Comment by tonsky** [comment]
Try `clojure.core/re-pattern`

**Comment by jenyckee** [comment]
Still Unknown function

**Comment by tonsky** [comment]
Are you running this from Clojure or ClojureScript? If the latter, you’ll need to pass fn as another input `:in $ ?re-pattern` and then call it as `[(?re-pattern ?matcher) ?regex]`

**Comment by jenyckee** [comment]
I am running this from the Javascript API

```
ds.q(`[:find ?e :where :in $ ?re-pattern
    [?e ":person/Voornaam" "${name}"]
    [(str "${name}" ?match) ?matcher]
    [(?re-pattern ?matcher) ?regex]
    [(re-find ?regex ?aname)]
    [?e :person/Voornaam ?aname]
    ]
    `
  ,db, [e => e])
```

**Comment by tonsky** [comment]
Yeah, you can’t use it because it was not bundled with the JS file unfortunately. You can use JS to construct the pattern you need though, ClojureScript regexes are just JS regexes

**Comment by jenyckee** [comment]
So why does this not give me the list of id's that match `name`?
```

  const reMatch = (e) => new RegExp(e)

  return ds.q(`[:find ?e 
    :in $ ?re-pattern :where 
    [(str "${name}" ?match) ?matcher]
    [(?re-pattern ?matcher) ?regex]
    [(re-find ?regex ?aname)]
    [?e ":person/Voornaam" ?aname]]`
  , state.db, reMatch)
```

**Comment by tonsky** [comment]
maybe because it doesn‘t know what `?match` is

**Comment by jenyckee** [comment]
Why do I get 

`Error: Cannot compare fetching to :person/Voornaam
`
in
```
'[:find ?e :in $ [?name ?rematch] :where
    [?e :person/Voornaam ?name]]
```

**Comment by tonsky** [comment]
You can’t mix string and keyword attributes
