### ISSUE TITLE
Transaction report :tempids does not always contain all tempids

### ISSUE THREAD

**Issue by kennyjwilli** [tonsky/datascript#246]
If you use a map form in a transaction without including a `:db/id`, one is automatically created for the entity but it is not included in the `:tempids` key in the transaction report. Example:

```clojure
(-> (d/empty-db)
    (d/with [{:foo "a"}]))
=>
#datascript.db.TxReport{:db-before #datascript/DB{:schema nil, :datoms []},
                        :db-after #datascript/DB{:schema nil, :datoms [[1 :foo "a" 536870913]]},
                        :tx-data [#datascript/Datom[1 :foo "a" 536870913 true]],
                        :tempids #:db{:current-tx 536870913},
                        :tx-meta nil}
```

If you do the same transaction with a `:db/id` explicitly assigned, it is included:

```clojure
(-> (d/empty-db)
    (d/with [{:db/id -1
              :foo   "a"}]))
=>
#datascript.db.TxReport{:db-before #datascript/DB{:schema nil, :datoms []},
                        :db-after #datascript/DB{:schema nil, :datoms [[1 :foo "a" 536870913]]},
                        :tx-data [#datascript/Datom[1 :foo "a" 536870913 true]],
                        :tempids {-1 1, :db/current-tx 536870913},
                        :tx-meta nil}
```

If a tx-data map form does not include a `:db/id`, Datomic will automatically assign it one (like DataScript) *and* include it in the `:tempids` in the transaction report. 

Is there a reason this was implemented differently from Datomic? Would you accept a PR fixing this issue?

**Comment by tonsky** [comment]
tempids are there for you to being able to track back what ids were assigned to entities you care about. If you didn’t include `:db/id` in transaction, how do you expect to find it in tempids? Under which key?

**Comment by kennyjwilli** [comment]
I care about all the entities I am transacting. In my case, I don't have a need to explicitly assign a tempid before transacting. Really all I am after is getting a list of `:db/id`'s for entities that were created (not updated) from a transaction report. 

It looks like Datomic automatically assigns a tempid to all entities in the transaction that do not have a `:db/id`. Here is an example of transacting the map form without including a `:db/id`.

```clojure
(let [conn (d/connect db-uri)]
  @(d/transact conn [{:foo "a"}]))
=>
{:db-before datomic.db.Db,
 @af119e05 :db-after,
 datomic.db.Db @9bc720dd,
 :tx-data [#datom[13194139534327 50 #inst"2018-01-09T07:28:11.646-00:00" 13194139534327 true]
           #datom[17592186045432 69 "a" 13194139534327 true]],
 :tempids {-9223301668109598114 17592186045432}}
```

**Comment by tonsky** [comment]
Ok, for parity with Datomic we can implement the same behaviour. This is new behaviour—when DS was written, Datomic didn’t allow skipping db/ids at all

**Comment by filipesilva** [comment]
Hi there 👋 

I have a similar use case as well. While working on https://github.com/filipesilva/datafire I needed to have a translation layer to convert all numeric `:db/id` into a globally unique id. Part of that was identifying which new ids were being added in a given transaction.

Finding out the tempids was easy because they were included in the transaction report. But the automatic ids (the `:db/id` for new entities) weren't as easy and required checking individual datoms in the tx-data to see if that id was not in the db before.

I think the behaviour of having automatic ids under a new tempid entry (as in @kennyjwilli example) makes sense.

@tonsky would you be receptive to a contribution implementing this behaviour?

**Comment by tonsky** [comment]
> would you be receptive to a contribution implementing this behaviour

@filipesilva Yes please. I think it should work as this: for any entities without explicit :db/id that is created, we put an entry to a map that maps its eid to itself. E.g.

```
(-> (d/empty-db)
    (d/with [{:db/id -1, :foo "a"}
             {:foo "b"}])
    (:tempids))

; => {-1 1, 2 2}
```

(assuming second entity was assigned eid=2)

**Comment by filipesilva** [comment]
@tonsky submitted a PR that does this: https://github.com/tonsky/datascript/pull/337
