### ISSUE TITLE
Transformation function in datalog gets nil as argument?

### ISSUE THREAD

**Issue by sj4** [tonsky/datascript#250]
Whenever I try to use a regular Clojure function in a Datalog query, the query outputs nothing, or, if the function cannot handle nil as argument, a NullPointerException.

I'm trying to find out what I'm doing wrong, but I get stuck. Here is a minimal example
(Clojure 1.8.0, Datascript 0.16.3)  

This 
```clojure
'[:find ?x
     :in $
     :where
     [?x]]
```
returns all entity ids in the database. So far so good

Then, I would expect this to also return all entity ids in the database:

```clojure
'[:find ?y
     :in $
     :where
     [(clojure.core/identity ?x) ?y]
     [?x]]
```
but it returns an empty set

trying to find out what happens (ns: `myns`)...
```clojure
(defn identitydbg [x]
   (prn :dbg x) x)

'[:find ?y
     :in $
     :where
     [(myns/identitydbg ?x) ?y]
     [?x]]
```
output
```
:dbg nil
```
nobody else seems to complain, so I must be doing something wrong, but how to proceed?
Thanks in advance

**Comment by tonsky** [comment]
this happens because `?x` is a free variable at this point. It has no values. Change the order of statements, it’ll bind ?x to entity ids and after that you’ll be able to call your fn, because DataScript would know where to take ?x values from.

```
'[:find ?y
     :where
     [?x _ _]
     [(clojure.core/identity ?x) ?y]]
```

**Comment by sj4** [comment]
Thank you!
