### ISSUE TITLE
Integration with Hazelcast using j.u.Map and j.u.List Interface

### ISSUE THREAD

**Issue by corporatepiyush** [tonsky/datascript#256]
Can we use custom implementation of java.util.Map and java.util.List for Database instead of Clojure maps ?
It will help intergrate with Hazelcast's distributed memory grid and hence this library can used as query language to distributed and disk persisted database.

http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/List.html
http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/Map/Getting_Map_and_Putting_Entries.html

**Comment by tonsky** [comment]
DataScript relies on sorted sets (B+ trees in current impl) with range queries. Do they have anything like that?

**Comment by corporatepiyush** [comment]
Hazelcast supports java.util.Set 
http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/Set.html

so as long as any implementation conforms to java.util.Set interface that should work.

**Comment by corporatepiyush** [comment]
or else it can be done in reverse way. 
We can target the Protocol/Interface which datascript uses for Database operations and we can hook Hazelcast's distributed data structures into it and we will be able to create Datomic like distributed DB'

**Comment by tonsky** [comment]
Sorted set is not the same as just Set. Set is just yes/no, DataScript needs efficient ranges (all values from X to Y), and it needs custom comparison logic too

**Comment by corporatepiyush** [comment]
java.util.SortedSet can be implemented easily over Hazlecast's Set or Map (ignoring values)
https://docs.oracle.com/javase/8/docs/api/java/util/SortedSet.html

But the way I see it BTSet is not compatible to that interface either
https://github.com/tonsky/datascript/blob/master/src/datascript/btset.cljc

**Comment by tonsky** [comment]
Sorry, I don’t understand how could one implement sorted set over a set or a map?

**Comment by corporatepiyush** [comment]
By implementing the abstract methods in SortedSet interface
For example. java.util.TreeMap can accept anything which implements java.util.Map interface
https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html

Perhaps you are concerned about to carry over the same structure of BTSet to Hazelcast. That may not be possible and that's fine. 

If Hazelcast and its Data Structures sounds more confusing, lets focus on my basic requirement 
What I am interested in implementing
1.  **Adaptor Pattern**  - Adapt java.util.SortedSet methods into BTSet and utilize its methods internally 
or
2.  datascript accepts (different protocol/interface than java.util.SortedSet) which takes care of data retrieval and persistence through any other custom solution.

**Comment by wbrown-lg** [comment]
This would be particularly interesting for my use case.

Although I've taken the functional approach of just using Datascript as a source of useful functions for my own Datalog engine, such as the query parser, the hash-join functions.  Datascript fundamentally is a memory-based database, and I've shifted away from holding arrays in memory to applying matching and join functions against a custom-written lazy TupleStream interface.  This allowed me to deal with and return result sets measured in the gigabytes.

**Comment by corporatepiyush** [comment]
That's precisely what I am after, decouple query engine from storage layer.
Could you please share GIST if possible ? or perhaps library if you made it open source.
