### ISSUE TITLE
Issue with backward navigation

### ISSUE THREAD

**Issue by pedroteixeira** [tonsky/datascript#257]
Hello, I tried a simple example with backward navigation but did not work as I expected:

// using the js API (v0.16.4)
```
db = datascript.empty_db({"collection/children": {
  ":db/cardinality": ":db.cardinality/many",
  ":db/valueType": ":db.type/ref",
  ":db/isComponent": true
}})

db = datascript.db_with(db, [ 
  [":db/add", 1, "collection/children", 2],
  [":db/add", 2, "name", "2"]
])
```

```
e = datascript.entity(db, 1)
child = e.get('collection/children')[0]
parent = child.get('collection/_children')[0]
```

I expected that `parent.get(':db/id') === e.get(':db/id') === 1`  but `parent` here ends being a native clj array of `["collection/children, [child] ]` but with no access to the parent entity itself.

Is this expected? I tried with the native clj entity API and got same result
I couldn't see what's wrong with this simple case (and a datalog query works).
Any ideas / hints?

thank you for the great library!

**Comment by tonsky** [comment]
What does `child.get('collection/_children')` returns? I suspect that if relationship is marked as `:db/isComponent` then walking it backwards returns single entity, not a collection (for normal references it would be a collection)

**Comment by pedroteixeira** [comment]
`child.get('collection/_children')` is returning a native js array :/

**Comment by pedroteixeira** [comment]
@tonsky btw, do you already have unit test for something like this, i.e. nav back then forward?
Because I'm still not sure if just a "local issue" of mine. I'll try to use to use the datoms index directly for now.

**Comment by tonsky** [comment]
Yes I have
https://github.com/tonsky/datascript/blob/4df745223ad6c799f6a5887b598a72e4e5c60181/test/js/tests.js#L278-L283

**Comment by pedroteixeira** [comment]
Ok, I remebered that I'm using the datascript module exported from https://github.com/typeetfunc/datascript-mori 

Since you have the unit tests, I will close this issue, probably something else interfering.
Thanks for replying.
