### ISSUE TITLE
Doc strings for datascript.core

### ISSUE THREAD

**Issue by fversnel** [tonsky/datascript#258]
Hi @tonsky,

Your blogposts and datascript have taught me a lot on how to design applications and I would love to give something back to the community. Would you be interested in a PR with doc strings for the datascript.core API? Up until now I've mostly resorted to the wiki and the code to figure things out and I think doc strings could enrich the user experience.

Kind regards,
Frank

**Comment by tonsky** [comment]
Added in https://github.com/tonsky/datascript/commit/5cf55d6fb40d8578728229675e566c8e5255d0b2
