### ISSUE TITLE
Persistence example

### ISSUE THREAD

**Issue by ghost** [tonsky/datascript#26]
Would be helpful to sneak this into the tutorials as an persistence (even if it's just for the life-time of the browser) example:

```
(cljs.reader/register-tag-parser! "datascript/DB" d/db-from-reader)
(->> conn d/db str (aset js/sessionStorage "last-state"))
(->> "last-state" (aget js/sessionStorage) cljs.reader/read-string atom)

```

**Comment by tonsky** [comment]
Now there’s [Tips&tricks page](https://github.com/tonsky/datascript/wiki/Tips-&-tricks) which has EDN serialization example and link to [transit serialization](https://github.com/tonsky/datascript-transit)

**Comment by fasiha** [comment]
Sorry to comment on this old issue. Is there a recommended way to persist on JVM? The most straightforward way I can think of is "periodically spit db to /tmp/random-file, then move /tmp/random-file to mydb.edn, overwriting the latter". If there was a way to avoid spitting the entire db when only a single fact changed, that'd be a nice optimization—i.e., overwrite only the portions of the file that changed.

**Comment by tonsky** [comment]
No good way yet, sorry

**Comment by theronic** [comment]
Assuming sparse per-user data, I think a consistent (even if non-performant) DataScript persistence story for user-data + small global facts stored in H2, Firebase or Postgres (on Heroku) would go a long way to encouraging DataScript adoption for its intended use. I've considered making a Firebase adapter keyed on user id, e.g. `/users/tonsky/eavt`, `/users/tonsky/avet` etc. where each client maintains their own indexes, just so I don't have to do the whole Datomic thing. Sure, if you're doing event streams/CQRS, could just store and re-run these, but making DataScript seamless would be super tasty :)
