### ISSUE TITLE
Support :db/retractEntity

### ISSUE THREAD

**Issue by kennyjwilli** [tonsky/datascript#265]
With the release of Datomic Cloud, `:db.fn/retractEntity` has been renamed to `:db/retractEntity` ([docs](https://docs.datomic.com/cloud/transactions/transaction-functions.html#sec-1)). For parity with the Datomic API, would you accept a PR adding support for `:db/retractEntity`?

**Comment by tonsky** [comment]
Yes. :db/cas as well
