### ISSUE TITLE
IPersistentMap implementation for Entity

### ISSUE THREAD

**Issue by darkleaf** [tonsky/datascript#284]
Is it useful to implement IPersistentMap for Entity?

```clojure
(-> (d/empty-db)
    (d/entity 1) ;; will return empty instead nil
    (assoc :key :value)
    (assoc :key2 :value2)
    (dissoc :key :value)
    (update in [:ref :multi] conj 1)
    (d/entity-db)) ;; get changed DB
```

There are some unobvious things:

+ blank entity object for not existed entity 
+ `(assoc e :field nil)` will retract datom
+ references
+ etc

**Comment by tonsky** [comment]
I prefer entity to stay read-only interface.
