### ISSUE TITLE
Conflicting upsert when ids are added out of order

### ISSUE THREAD

**Issue by Cortys** [tonsky/datascript#285]
Upserts fail if multiple tempids are first allocated and then unified in a different order:
```clojure
(d/db-with (d/empty-db {:name {:db/unique :db.unique/identity}})
           [[:db/add -1 :age 42]
            [:db/add -2 :likes "Pizza"]
            [:db/add -2 :name "Bob"]
            [:db/add -1 :name "Bob"]])
;; => Fails: Conflicting upsert: -1 resolves both to 3 and 2
```

If however unification happens in the same order as the initial allocation, the issue does not occur:
```clojure
(d/db-with (d/empty-db {:name {:db/unique :db.unique/identity}})
           [[:db/add -1 :age 42]
            [:db/add -2 :likes "Pizza"]
            [:db/add -1 :name "Bob"]
            [:db/add -2 :name "Bob"]])
;; => Works.
```

Is this a bug or intentional (i. e. similar to #172)?

**Comment by tonsky** [comment]
It’s strange that second way works. Are you sure it does what you want? Tempid resolution in DS is top-to-bottom, with no backtracing, so changing this behaviour (adding unification) would need a huge refactoring.

**Comment by Cortys** [comment]
Yes, it seems to work as expected irrespective of the number of unified tempids:
```clojure
(deftest unification
  (let [n 100
        db (d/db-with (d/empty-db {:x {:db/cardinality :db.cardinality/many}
                                   :key {:db/unique :db.unique/identity}})
                      (concat ; Allocate n tempids:
                              (map #(vector :db/add (- %) :x %) (range n))
                              ; Unify them:
                              (map #(vector :db/add (- %) :key "foo") (range n))))]
    ; All n tempids are resolved to the same entity:
    (is (= (d/pull db '[*] [:key "foo"])
           {:db/id 0 
            :key "foo"
            :x (vec (range n))}))))
```

As far as I understand this works because [`retry-with-tempid`](https://github.com/tonsky/datascript/blob/2b00e5aaadfad28cddccd1039020d02c0ea0d170/src/datascript/db.cljc#L1176) is called after each addition of `:id`.
This effectively unifies one tempid `-t` with `[:id "foo"]` at a time. The old entity id `allocated-id` that `-t` was assigned via `[:db/add -t :x t]` is replaced with `upserted-id`, i.e. the id of `[:id "foo"]`.

In total this performs `O(n^2)` operations but at least it works reliably. I'm however not quite sure why the unification order matters.

**Comment by tonsky** [comment]
Right! I forgot about this. I’ll take a closer look into the issue soon
