### ISSUE TITLE
Inconsistent upsert behavior with large db/id values

### ISSUE THREAD

**Issue by tomconnors** [tonsky/datascript#292]
Upsert doesn't appear to work correctly in cljs when the db/id value is big. I'm seeing this in 0.18.1 but not in 0.16.6 (haven't tested any in-between versions).

cljs, non-upsert (no issue here):
``` clojure
cljs.user> (def conn (datascript.core/create-conn {}))
#'cljs.user/conn
cljs.user> (datascript.core/transact! conn [{:entity/name "foo"}])
#datascript.db.TxReport{:db-before #datascript/DB {:schema {}, :datoms []}, :db-after #datascript/DB {:schema {}, :datoms [[1 :entity/name "foo" 536870913]]}, :tx-data [#datascript/Datom [1 :entity/name "foo" 536870913 true]], :tempids {:db/current-tx 536870913}, :tx-meta nil}
cljs.user> (datascript.core/touch (datascript.core/entity @conn 1))
{:entity/name "foo", :db/id 1}
cljs.user> (datascript.core/q '[:find ?e ?name :where [?e :entity/name ?name]] @conn)
#{[1 "foo"]}
```

cljs, upsert w/ small id (no issue here):
``` clojure
cljs.user> (def conn (datascript.core/create-conn {}))
#'cljs.user/conn
cljs.user> (datascript.core/transact! conn [{:entity/name "foo" :db/id 100}])
#datascript.db.TxReport{:db-before #datascript/DB {:schema {}, :datoms []}, :db-after #datascript/DB {:schema {}, :datoms [[100 :entity/name "foo" 536870913]]}, :tx-data [#datascript/Datom [100 :entity/name "foo" 536870913 true]], :tempids {:db/current-tx 536870913}, :tx-meta nil}
cljs.user> (datascript.core/touch (datascript.core/entity @conn 100))
{:entity/name "foo", :db/id 100}
cljs.user> (datascript.core/q '[:find ?e ?name :where [?e :entity/name ?name]] @conn)
#{[100 "foo"]}
```

cljs, upsert w/ large id - this is where the inconsistency is
``` clojure
cljs.user> (def conn (datascript.core/create-conn {}))
#'cljs.user/conn
cljs.user> (datascript.core/transact! conn [{:entity/name "foo" :db/id 285873023227265}])
#datascript.db.TxReport{:db-before #datascript/DB {:schema {}, :datoms []}, :db-after #datascript/DB {:schema {}, :datoms []}, :tx-data [#datascript/Datom [285873023227265 :entity/name "foo" 536870913 true]], :tempids {:db/current-tx 536870913}, :tx-meta nil}
cljs.user> (datascript.core/touch (datascript.core/entity @conn 285873023227265))
{:entity/name "foo", :db/id 285873023227265}
cljs.user> (datascript.core/q '[:find ?e ?name :where [?e :entity/name ?name]] @conn)
#{}
```

On clj, all three work as expected.
``` clojure
;; clj, not upsert:
user> (def conn (datascript.core/create-conn {}))
#'user/conn
user> (datascript.core/transact! conn [{:entity/name "foo"}])
{:db-before {},
 :db-after {1 :entity/name},
 :tx-data [#datascript/Datom [1 :entity/name "foo" 536870913 true]],
 :tempids #:db{:current-tx 536870913},
 :tx-meta nil}
user> (datascript.core/touch (datascript.core/entity @conn 1))
{:entity/name "foo", :db/id 1}
user> (datascript.core/q '[:find ?e ?name :where [?e :entity/name ?name]] @conn)
#{[1 "foo"]}

;; clj, upsert, small id:
user> (def conn (datascript.core/create-conn {}))
#'user/conn
user> (datascript.core/transact! conn [{:entity/name "foo" :db/id 100}])
{:db-before {},
 :db-after {100 :entity/name},
 :tx-data
 [#datascript/Datom [100 :entity/name "foo" 536870913 true]],
 :tempids #:db{:current-tx 536870913},
 :tx-meta nil}
user> (datascript.core/touch (datascript.core/entity @conn 100))
{:entity/name "foo", :db/id 100}
user> (datascript.core/q '[:find ?e ?name :where [?e :entity/name ?name]] @conn)
#{[100 "foo"]}
user> 

;; clj, upsert, big id:
user> (def conn (datascript.core/create-conn {}))
#'user/conn
user> (datascript.core/transact! conn [{:entity/name "foo" :db/id 285873023227265}])
{:db-before {},
 :db-after {285873023227265 :entity/name},
 :tx-data
 [#datascript/Datom [285873023227265 :entity/name "foo" 536870913 true]],
 :tempids #:db{:current-tx 536870913},
 :tx-meta nil}
user> (datascript.core/touch (datascript.core/entity @conn 285873023227265))
{:entity/name "foo", :db/id 285873023227265}
user> (datascript.core/q '[:find ?e ?name :where [?e :entity/name ?name]] @conn)
#{[285873023227265 "foo"]}
```

**Comment by claj** [comment]
I didn't know but bitwise operations in javascript limits the result to 32 bits:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators

Your eid 285873023227265 has the following bit representation (without any padding)
(Long/toBinaryString 285873023227265)
"1000001000000000000000000000000000001010110000001"
user> (count (Long/toBinaryString 285873023227265))
49

I suspect your eids get cut at 32 bits in the bit operations which sort of works as long as it is made consistent.

I suspect you are using Datomic eids in your datascript db. It's usually better to introduce some external and more controllable index when syncing between these to different databases.

**Comment by tomconnors** [comment]
Yes, I am using datomic eids on the frontend, and I agree I should stop doing that.

IMO datascript should either explicitly not support longs as :db/id values by documenting the accepted values and throwing if values outside that range are used or the current behavior should be considered a bug.

**Comment by tonsky** [comment]
I can’t check if you are using integers that don’t exist in JavaScript because you can’t represent them in JavaScript :)

**Comment by tomconnors** [comment]
Not sure I understand. 285873023227265 is a valid number in js, it just happens to be larger than a 32 bit int. So couldn't datascript just complain if given an entity id above 2,147,483,647? Or, ideally, accept any valid js number as an entity id.
If this is a wontfix type of thing, maybe a note about it in the docs would help someone in my situation in the future.

**Comment by tonsky** [comment]
Yeah, sorry, I confused 2^53 (upper limit for JS integers) and 2^32 (fast JS integers). I’m not sure where bit operations come from, I’ll have to check.

**Comment by claj** [comment]
I would suspect the bit shifts in the bt-set, where they are picked out to be used as indexes in the nested bransch-arrays:

https://github.com/tonsky/persistent-sorted-set/blob/0683019c890de91b375baf4c7c8523d16d586e2a/src-clojure/me/tonsky/persistent_sorted_set.cljs#L46

**Comment by tonsky** [comment]
It seems that long ids are no longer supported on JVM since 0.18.0. I also added a validation that throws on both JVM and JS if value is out of range.
