### ISSUE TITLE
Inconsistent return types in clojure.data/diff tuple

### ISSUE THREAD

**Issue by kennyjwilli** [tonsky/datascript#296]
I expected the result of `diff` to be a tuple of a list of Datoms or `nil` for things-only-in-a, things-only-in-b, and things-in-both. things-in-both is allowed to be a list of Datoms, `nil`, or a `DB`. Is this expected?

**Expected return type**
Actual return type: 
`[([datascript/Datom] | nil) ([datascript/Datom] | nil) ([datascript/Datom] | nil) ]`

**Actual return type** 
`[([datascript/Datom] | nil) ([datascript/Datom] | nil) ([datascript/Datom] | datascript/DB | nil) ]`

**Examples**

```clojure
(clj-data/diff
  (d/db-with (d/empty-db) [])
  (d/db-with (d/empty-db) []))
=> [nil nil #datascript/DB{:schema nil, :datoms []}]
```

```clojure
(clj-data/diff
  (d/db-with (d/empty-db) [{:a "a"}])
  (d/db-with (d/empty-db) [{:a "a"}]))
=> [nil nil #datascript/DB{:schema nil, :datoms [[1 :a "a" 536870913]]}]
```

```clojure
(clj-data/diff
  (d/db-with (d/empty-db) [{:a "a"}])
  (d/db-with (d/empty-db) [{:a "a"}
                           {:b "b"}]))
=> [nil [#datascript/Datom[2 :b "b" 536870913 true]] [#datascript/Datom[1 :a "a" 536870913 true]]]
```

**Comment by tonsky** [comment]
Good catch! No, this is not expected. Probably a bug

**Comment by darkleaf** [comment]
https://github.com/clojure/clojure/blob/master/src/clj/clojure/data.clj#L138

**Comment by tonsky** [comment]
Looks like not much I can do :)
