### ISSUE TITLE
Query doesn't work under advanced optimizations

### ISSUE THREAD

**Issue by Lokeh** [tonsky/datascript#298]
```clojure
       (ds/q '[:find ?tx ?id ?v ?ts
               :where
               [?e :entry/value ?v ?tx]
               [?e :entry/id ?id ?tx]
               [?e :entry/ts ?ts ?tx]]
             app-db)
```

:point_up: this query doesn't work under advanced optimizations. any ideas why?

```clojure
#datascript/DB {:schema nil, :datoms [[1 :entry/id 15 536870914] [1 :entry/ts 1557849697260 536870914] [1 :entry/value {:value 1, :meta nil} 536870914]]}
```

is the DB for instance and that query returns `#{[nil nil nil nil]}`

**Comment by tonsky** [comment]
Works for me on

```
[org.clojure/clojure       "1.10.0"]
[org.clojure/clojurescript "1.10.520"]
```

what version of compiler are you on?

**Comment by Lokeh** [comment]
This was due to missing externs while using shadow-cljs. thheller pointed me to https://github.com/tonsky/datascript/pull/216; adding `:externs ["datascript/externs.js"]` to `:compiler-options` map in my `shadow-cljs.edn` fixed the issue for now.

Is there some place we can note this, if we can't remove the need for externs to be present under advanced optimizations?

**Comment by tonsky** [comment]
Well the idea of externs is that they _are_ absolutely required. Why else have them?

**Comment by Lokeh** [comment]
I'm not sure I understand. My point was that I had no idea that adding the externs to my project config was necessary. I was thinking that we could add a note to the installation instructions.

**Comment by tonsky** [comment]
Totally! shadow-cljs README should mention this for all CLJS projects!

**Comment by jamesnyika** [comment]
Confirming as well that this query 

```` 

(d/q '[:find [?e ...]
         :in $ ?attribute
         :where
          ;[?e :event/name] ;; I USED TO HAVE TO DO THIS
          [?e ?attribute]  ;; BUT NOW I CAN INSTEAD DO THIS
          [?e :event/active true]] ds attribute))

```` 
WORKS just by adding this to my shadow-cljs.edn file

````
...
 :compiler-options {:infer-externs :auto
                      :externs ["datascript/externs.js"]} ;; <--- just add this in
````

**Comment by jamesnyika** [comment]
I added a section under the wiki Tips & Tricks section.

**Comment by yqrashawn** [comment]
Hi,

I followed this issue and add those two `:compiler-options` to shadow-cljs config and found a `datascript is not defined` error.
It turns out the compiled `prod.js` defines datascript with `datascript={}` instead of `var datascript={}`.

Since my build target is `:esm`, having `datascript={}` kind of expression will cause the `datascript is not defined` error.

My solution is to add `:prepend-js "if(window)window.datascript={};"` to `shadow-cljs.edn` like bellow.

```clojure
{:target :esm
 ...
 :compiler-options {:infer-externs :auto
                    :externs ["datascript/externs.js"]}
 :modules {:app {:exports ...
                 :prepend-js "if(window)window.datascript={};"}
```

Just put it here in case someone encounters the same problem.

**Comment by tonsky** [comment]
@yqrashawn I am not familiar with how shadow processes externs. Does it simply prepends them? Do you think externs bundled with DataScript should be changed (e.g. datascript -> global.datascript?)

**Comment by yqrashawn** [comment]
I'm not familiar with closure compiler. I tried this in externs.js file. It's not work. Closure compiler still compiles it to `;datascript={}` in the outmost scope of a ESM js file. 

I guess closure compiler don't know about that user is going to use the file in as a ESM file, only shadow-cljs knows about it.
```js
if (global) global.datascript = datascript
else if (window) window.datascript = datascript
else {
  var datascript = {}
}
```

**Comment by logseq-cldwalker** [comment]
@yqrashawn Thanks for the snippet. I wasn't able to use it in `:prepend-js` as I get this error - https://github.com/google/closure-compiler/wiki/FAQ#i-got-a-partial-alias-created-for-namespace-error--what-do-i-do . I was able to use your snippet with `:prepend` e.g.:

```clojure
:prepend "if (global) { global.datascript = datascript } else if (window) { window.datascript = datascript } else { var datascript = {}}"
```
