### ISSUE TITLE
Trivial entities have side-effects in transactions

### ISSUE THREAD

**Issue by abrooks** [tonsky/datascript#314]
## Behavior
Considering the following:

```clojure
=> (let [conn (d/create-conn {})]
       (d/transact! conn [#:db{:id 1001}
                          #:db{:id -10}
                          {}
                          {:db/id -9, :name "Jane Doe"}
                          {:db/id 1004, :age 9}])
       (clojure.pprint/pprint (seq @conn)))
(#datascript/Datom [1004 :age 9 536870913 true]
 #datascript/Datom [1004 :name "Jane Doe" 536870913 true])
nil
```
This test case (actually, a much hairier version) arose in using datascript as a generative test oracle for some enhancements we are developing for [clara-eav](https://github.com/clyfe/clara-eav/issues/2) which provides a Datomic/datascript mode for interacting with EAV values on top of Clara rules. While it's not the sort of  case that would likely appear in hand written transactions, it is quite reasonable to come across in some automated cases where entity maps are generated or otherwise transformed by code.

This behavior (emitting a single entity with two attributes when two, distinct entities would be expected) highlights what I see as two misbehaviors.

#### Trivial entities have side-effects in transactions
In the example above, I include three trivial entities (though only the first is needed for the bug in this case) to show two, closely related side-effects. The first entity map, though it does not actually produce any entities in the DB (because it has no attributes) still bumps the `:max-eid` with a real eid in the report. The second entity map does the same but via the `tempid?` path. The third entity map also does the same but via the `nil?` path.

#### Collisions between tempids and real eids in a transaction
This is more of a design approach question and, depending on your inclination, would warrant a separate ticket to be filed if it is deemed a misfeature. In brief, even without the trivial map side -effects, in the current implementation, a tempid can be generated that coincides with the eid of a subsequent entity or tuple form later in the transaction. In the 

## Proposal
I am happy to submit a pull request to filter out entity maps which contain no attribute-values (and would therefore not transact anything in to the database). I'd also include test cases.

I am also happy to discuss approaches to avoiding tempid/eid collisions. I can file a separate ticket for this if it is of interest.

**Comment by tonsky** [comment]
> a tempid can be generated that coincides with the eid of a subsequent entity or tuple form later in the transaction

This is fine. You are not supposed to insert new entities by providing an eid. You can, but if you do, I suppose you know what you are doing.

> I am happy to submit a pull request to filter out entity maps which contain no attribute-values.

Please do

**Comment by tonsky** [comment]
I decided not to do anything about it. There’s no harm in trivial entities bumping next eid, but it will complicate the code. If this is a problem for you, you can always pre-filter your transaction before feeding it to the DataScript.
