### ISSUE TITLE
Exception thrown when lookup ref used in pull

### ISSUE THREAD

**Issue by kennyjwilli** [tonsky/datascript#315]
When I `d/pull` an entity using a lookup ref, an exception is thrown if the entity does not exist. This behavior does not match the behavior of `d/pull` when passed a `:db/id`. Example cases:

`pull`'ing an entity that does not exist using a db/id.
```clojure
(d/pull (d/empty-db {:id {:db/unique :db.unique/value}})
        [:foo]
        2)
=> nil
```

`pull`'ing an entity that does not exist using a lookup ref: 
```clojure
(d/pull (d/empty-db {:id {:db/unique :db.unique/value}})
        [:foo]
        [:id "a"])
Error: Nothing found for entity id [:id "a"]
```

Is there a reason the behavior is different? FWIW, Datomic does not throw an exception when `pull`'ing an entity that does not exist via lookup ref.

**Comment by tonsky** [comment]
No specific reason, just emerging behaviour I guess. Happy to accept patch to bring it in line with what Datomic does

**Comment by tangjeff0** [comment]
+1 Just spent 2 hours debugging this in my app (which uses `posh`). Hopefully I can submit a PR to this as well.
