### ISSUE TITLE
Calling a rule that doesn't exist is quietly accepted

### ISSUE THREAD

**Issue by ash14** [tonsky/datascript#319]
Attempting to call a rule that doesn't exist (or mis-typed) does not sound an alarm, leading to unexpected results and hard to trace bugs:
```clj
(d/q '[:find ?e
       :in $ %
       :where (my-rule ?e)]
      (d/empty-db)
      '[])
=> #{}
```

The equivalent setup Datomic will throw a 
`java.lang.IllegalArgumentException: Cannot resolve key: my-rule`

**Comment by tonsky** [comment]
I agree! Will fix that eventually. Thanks
