### ISSUE TITLE
how to do reverse pull from JS client?

### ISSUE THREAD

**Issue by gdanov** [tonsky/datascript#326]
Hi,
 My understanding is that reverse lookup pull (pull, navigating in the opposite direction) is supported?
 What would be the correct syntax when using JS client (via datascript-mori) where the keys are strings?

**Comment by tonsky** [comment]
Should be the same:

```
d.pull(db, '["_parent"]', eid);
```

**Comment by tonsky** [comment]
If keys are namespaced, you need to add `_` before the name part:

```
d.pull(db, '["user/_parent"]', eid);
```

**Comment by gdanov** [comment]
thank you, this works as expected.  I was totally confused how strings are converted to clojure keywords and wasn't aware "my/keyword" well be converted to 'native' CLJ keyword. Would be nice if this is explicitly explained (or if already explained, made more prominent)

**Comment by tonsky** [comment]
If I ever have a user documentation, I will explain it there. For now it’s just the test suite you can consult
