### ISSUE TITLE
datascript/entity returns entities that do not exist

### ISSUE THREAD

**Issue by filipesilva** [tonsky/datascript#329]
The [docs for entity](https://cljdoc.org/d/datascript/datascript/0.18.7/api/datascript.core#entity) mention: 

```
If entity does not exist, nil is returned:

(entity db -1) ; => nil
```

But attempting to retrieve an entity that doesn't exist will actually return something, and attempting to retrieve `-1` as per the example will throw an error:
```
(datascript/entity @(datascript/create-conn) 1)
;; => {:db/id 1}
(datascript/entity @(datascript/create-conn) -1)
;; Error "Expected number or lookup ref for entity id, got -1"
```

I saw this behaviour while the 0.18.7 version of Datascript.

**Comment by tonsky** [comment]
Thanks! I guess at some point I added extra check and negative integers are not considered valid entid anymore. Positive, non-existing integer would still return nil. I’ll update the docs.

**Comment by filipesilva** [comment]
Thanks for the quick reply! 

In my testing a positive non-existing integer doesn't return nil right now though.

```
(datascript/entity @(datascript/create-conn) 1)
;; => {:db/id 1}
(datascript/entity @(datascript/create-conn) 100500)
;; => {:db/id 100500}
```

So I think there's still something wrong, and that it's not just a docs problem.

**Comment by tonsky** [comment]
Hmm. Ok I’ll look into it in more details. In any case, the solution would be to make it behave how Datomic behaves

**Comment by filipesilva** [comment]
I don't use datomic myself so I'm not sure what the matching behaviour is... but I agree it should match. Thanks for taking the time!

**Comment by claj** [comment]
I must confirm that Datomic returns an empty entity when given an entity id which do not exist.
 
```
(let [db (d/db (new-mock-conn))]
  [(d/touch (d/entity db -124)) ;; negative
   (d/touch (d/entity db 125)) ;; existing attribute
   (d/touch (d/entity db 125123123))]) ;;entity id which do not exist
=>
[#:db{:id -124}
 #:db{:id 125, 
     :ident :query-param/val, 
     :valueType :db.type/string, 
     :cardinality :db.cardinality/one}
 #:db{:id 125123123}]
```

This means essentially that negative numbers just returns an empty entity with the `:db/id`, wether it exists or not. I think I've read somewhere this is to make datomic compatible "future proof" in the sense that when you have your entity added or removed in the future, you should still be able to go back in history and just find an empty entity.

`d/entid` shows a similar behaviour, while `d/ident` returns nil for all entities not having a `:db/ident`(which is a concept that Datascript not have as one of its default attributes).

**Comment by filipesilva** [comment]
@claj do you know what the preferred mechanism for checking existence is instead of `entity`?

**Comment by claj** [comment]
Entities are just a view/navigation pattern of the datom indexes.

A query gives the existence of an attribute by looking into the datoms. An "empty" :db/id does not have any representation in the datoms.

One way to check for existence would be to use something like 

`(not (empty? (d/entity db :eavt entity-id)))`

which gives `true` if no data is added to the entity. An entity cannot be created without any attributes on it's own (links from other entities are not enough). If one tries to transact a temp-reference that does not have any attributes on its own, one gets the error message 

```
Execution error (Exceptions$IllegalArgumentExceptionInfo) at datomic.error/arg (error.clj:79).
:db.error/tempid-not-an-entity tempid '-9223350046622220289' used only as value in transaction

```
It's therefore not possible to have an empty "placeholder" entity without any attributes at all. It's not a problem in practice, all entities benefits from some kind of external index if no data is aligned to the entity.

I haven't looked into how Datascript handles transactions (lately) but Datomic would not accept links or `:db/add`s to empty (non-existent) entity-ids. All (user created) entities must be constructed via a temporary id always. Datascript can be more loose in this matter, which is usually not a problem.

**Comment by filipesilva** [comment]
`entity` shows in the [docs](https://cljdoc.org/d/datascript/datascript/0.18.7/api/datascript.core#entity) as only accepting two values. Did you mean `datoms` instead? 

`(d/datoms db :eavt entity-id)` will return the entity or nil, which is what I was using at the moment and looks like a good way of checking existence.

**Comment by claj** [comment]
Updated my answer with replacing `entity` to `datoms`.

`datoms` does returns not `nil`, but some reified collection printed like `datomic.db$datoms$reify__4003`, which is never `nil`. `(seq (d/datoms db :eavt non-existing-id))` returns `nil` if there is datoms in the reified collection of datoms, though.

**Comment by tonsky** [comment]
Yes, `entity` does not check if entity exists or not if you provide a numeric eid. What it does is just wrapping that eid in Entity class and waiting for you to try to pull any properties. I believe it was done to save some performance: `(d/entity id)` is always almost a free call, only accessing actual properties hits the database. If you decided not to use that entity, well, it costet you nothing.

To check entity existence, do something that touches the database. `(seq (d/datoms db :eavt non-existing-id))` or `(d/pull db [:db/id] eid)` or even `(:attr (d/entity db eid))` (if you know in advance that your entity MUST have the `:attr` attribute)

**Comment by filipesilva** [comment]
In datascript, `datoms` will return `nil` if nothing is found:
```
(d/datoms @(d/create-conn) :eavt 1)
;; => nil
```

I suppose that might be a difference from datomic. It doesn't make much difference in my case, just thought I'd test it.
