### ISSUE TITLE
Warn on unindexed :avet seq `(d/datoms db :avet ...)` instead of => nil

### ISSUE THREAD

**Issue by theronic** [tonsky/datascript#344]
`(d/datoms db :avet :some-attr)` returns nil if `:some-attr` is unindexed. This is mentioned in the docs, but it's caught me twice now. Would it be possible for `d/datoms` to warn me when trying to seq over an unindexed attribute, or perhaps trigger a slow scan instead of returning nil?

**Comment by tonsky** [comment]
Probably a good point. I think it should throw. d/datoms is index access, if there’s no index, no point emulating it. PR?
