### ISSUE TITLE
Or-clause with binding

### ISSUE THREAD

**Issue by hden** [tonsky/datascript#348]
Error

```
clojure.lang.ExceptionInfo: Join variable not declared inside clauses: [?age]
```

Code
```clj
(def test-db
  (delay
    (d/db-with (d/empty-db)
      [ {:db/id 1 :name "Ivan" :age 10}
        {:db/id 2 :name "Ivan" :age 20}
        {:db/id 3 :name "Oleg" :age 10}
        {:db/id 4 :name "Oleg" :age 20}
        {:db/id 5 :name "Ivan" :age 10}
        {:db/id 6 :name "Ivan" :age 20}])))

(deftest test-or-binding
  (is (= (into #{} (map vector) (d/q '[:find ?e
                                       :in $ ?age
                                       :where (or [?e :name "Oleg"]
                                                  [?e :age ?age])]
                                     @test-db 10))
         #{1 3 4 5})))
```

**Comment by tonsky** [comment]
What are you trying to do? `?age` is output variable in one clause, but is not present in the other. That way `or` sometimes will set it, but sometimes won’t. DataScript can’t have it half-defined, that’s why you get the error message

**Comment by hden** [comment]
@tonsky I am trying to get all the entities with either "Oleg" as name or 10 years old.

**Comment by tonsky** [comment]
Ok I get it now. The use-case seems valid. Datomic, though, find it wrong too:

```
(d/q '[:find ?e
       :in $ ?age
       :where (or
                [?e :name "Oleg"]
                [?e :age ?age])]
     (d/db conn) 10)
Execution error (AssertionError) at datomic.datalog/unifying-vars (datalog.clj:825).
Assert failed: All clauses in 'or' must use same set of vars, had [#{?e} #{?age ?e}]
(apply = uvs)
```

But in Datomic you can get around it by using `or-join`:

```
(d/q '[:find ?e
       :in $ ?age
       :where (or-join [?e ?age]
                [?e :name "Oleg"]
                [?e :age ?age])]
     (d/db conn) 10)
#{[17592186045418] [17592186045420] [17592186045421] [17592186045422]}
```

In DataScript it doesn’t work though. So it’s a valid bug. Thank you! Would love to take a PR on this one!

**Comment by hden** [comment]
The parser will try to validate the or-clause using the required and free vars. ([code](https://github.com/tonsky/datascript/blob/master/src/datascript/parser.cljc#L526-L531)). In this case, the **free** variable are actually bounded by the input variables.

To exclude the bounded variable...
1. We could pass-down the context (i.e. bounded variables) from the up.
2. We could also move the validation logic to the upper layer e.g. the validate-query function.

Let me know if my hypothesis sounds right. 

The stack trace:

```
ERROR in (test-or-join) (parser.cljc:497)
expected: (= (d/q (concat (quote [:find ?e :in $ ?a ?n :where]) (quote [(or-join [?e ?a ?n] [?e :age ?a] [?e :name ?n])])) (clojure.core/deref test-db) 10 "Ivan") (into #{} (map vector) #{1 6 3 2 5}))
  actual: clojure.lang.ExceptionInfo: Join variable not declared inside clauses: [?n]
 at
datascript.parser/-validate-join-vars (parser.cljc:497)
    datascript.parser/-validate-join-vars (parser.cljc:494)
    datascript.parser/validate-join-vars (parser.cljc:505)
    datascript.parser/validate-join-vars (parser.cljc:503)
    datascript.parser$validate_or$fn__3454.invoke (parser.cljc:547)
    datascript.parser/validate-or (parser.cljc:546)
    datascript.parser/validate-or (parser.cljc:540)
    datascript.parser/-parse-or-join (parser.cljc:585)
    datascript.parser/-parse-or-join (parser.cljc:576)
    datascript.parser/parse-or-join (parser.cljc:591)
    datascript.parser/parse-or-join (parser.cljc:589)
    datascript.parser/parse-clause (parser.cljc:629)
    datascript.parser/parse-clause (parser.cljc:624)
    datascript.parser$parse_seq$fn__2503.invoke (parser.cljc:51)
    datascript.parser/parse-seq (parser.cljc:51)
    datascript.parser/parse-seq (parser.cljc:49)
    datascript.parser/parse-clauses (parser.cljc:638)
    datascript.parser/parse-clauses (parser.cljc:637)
    datascript.parser/parse-where (parser.cljc:641)
    datascript.parser/parse-where (parser.cljc:640)
    datascript.parser/parse-query (parser.cljc:770)
    datascript.parser/parse-query (parser.cljc:759)
    datascript.query/memoized-parse-query (query.cljc:902)
    datascript.query/memoized-parse-query (query.cljc:899)
    datascript.query/q (query.cljc:907)
    datascript.query/q (query.cljc:906)
    datascript.test.query_or$fn__4618$fn__4627.invoke (query_or.cljc:85)
    datascript.test.query-or/fn--4618 (query_or.cljc:85)
    datascript.test.query-or/fn--4618 (query_or.cljc:70)
```

**Comment by tonsky** [comment]
I think the problem here happens even before we try to check who is free and who is bound (if we even do that check, not sure). The way `validate-join-vars` is called, it checks that ALL vars must be present in each of the `or` branch. But in reality the rule is trickier:

In `or-join`, all free vars must be present, but only arbitrary subset of required ones. Lists of both free and required are user-specified, so the check here is purely syntactical: `(or-join [[required+] free+] ...)`

In normal `or`, logic dictates that it’s ok to use different subsets of bound vars but exactly the same list of free ones in every branch. Parser has no access to that info, so we just make sure full list of vars is the same in each branch.

That matches Datomic behavior, I think. But `or-join` is implemented incorrectly in DataScript.

**Comment by tonsky** [comment]
Please take a look at https://github.com/tonsky/datascript/commit/e6f344f4da84ebfa0f26fa960198e62ca4a38b93, would it work for you?

**Comment by tonsky** [comment]
After more thinking, I think you are right. This should be solved with regards to actual bound/unbound vars, not on parser validation

**Comment by tonsky** [comment]
Ok I managed to move the check to query.cljc instead of parser, mainly because it already had infrastructure for bound/free checks in place. I also went an extra mile and checked only actually free vars, ignoring bound ones, in `or` branches. Unlike Datomic, `(or [?e :name "Oleg"] [?e :age ?age])` should work now without requiring manual var list in `or-join`.

Please take a look, if you are happy, I’ll cut a release.

**Comment by hden** [comment]
Awesome! I've tested it locally. Thank you!

**Comment by tonsky** [comment]
Cool. Just pushed 0.18.12
