### ISSUE TITLE
How to remove a data ? like ` :db/add => :db/remove`

### ISSUE THREAD

**Issue by chanshunli** [tonsky/datascript#352]
I am not find in https://github.com/tonsky/datascript/tree/master/test/datascript/test.

it's like this: `[[:db/retract eid :content]]` ? 

can i remove a entity?

**Comment by tonsky** [comment]
There are three functions:

```
[[:db/retract eid :attr value]]
[[:db.fn/retractAttribute eid :attr]]
[[:db/retractEntity eid]]
```

First removes specific attribute value.
Second one removes any value on an attribute.
Third one removes entity entirely.

**Comment by chanshunli** [comment]
@tonsky Thanks for your help 👍 👍 👍 💯
