### ISSUE TITLE
Add :db/retract with E A (not V)

### ISSUE THREAD

**Issue by claj** [tonsky/datascript#353]
Datomic has added another arity to retract.

From [0.9.6045: February 13, 2020](https://docs.datomic.com/on-prem/changes.html#0.9.6045)  `[:db/retract eid aid]` will retract all values for an eid/aid combination.

This should probably be implemented in datascript as well.

(inspired by issue #352 )

**Comment by tonsky** [comment]
Good idea, thanks!

**Comment by tonsky** [comment]
Fixed in 0.18.10 #339
