### ISSUE TITLE
When `find pull` use the nested map , how can pull nested map relation data?

### ISSUE THREAD

**Issue by chanshunli** [tonsky/datascript#354]
```clojure

(defn get-tree
  [current-id]
  (d/q '[:find  (pull ?root-nav
                  [:id :content :db/id
                   {:_parid ...}])
         :in $ ?current-id
         :where
         [?sub-nav :parid ?root-nav]
         [?sub-nav :id ?current-id]]
    @db/dsdb current-id))

```

the `@db/dsdb` is `#datascript/DB {:schema {...}  ...}`. 

call the `get-tree` will get the nested map data like this:

```clojure

{:db/id 4,
 :id "46376310-a7ad-11ea-9c98-fb9a71d5f3bb",
 :content "AAA",
 :_parid
 [{:db/id 2,
   :id "9b1d96ba-a7ad-11ea-8284-5b0dc85f01a8",
   :content "BBB"}
  {:db/id 3,
   :id "7ebd8192-a7ad-11ea-8385-5be8868d06cb",
   :content "CCC"}]}

```
if i add new entity to `@db/dsdb`, the `get-tree` can not pull this new entity data. 
i don't  know why. 
but, if i change any `:content` "AAA" or "BBB" or "CCC" , the `get-tree` can pull this new entity data.

**Comment by chanshunli** [comment]
i use the datascript version is "0.18.11".

**Comment by tonsky** [comment]
> if i add new entity

Can you share what exactly are you adding?
