### ISSUE TITLE
Retract should not compare cardinality one attr values

### ISSUE THREAD

**Issue by fversnel** [tonsky/datascript#356]
I have a very peculiar issue where the same tx-data (same exact clojure value) cannot be applied after is has been deserialized from a string. I get a:  

```
Execution error (ClassCastException) at datascript.db/cmp (db.cljc:317)
clojure.lang.PersistentArrayMap cannot be cast to java.lang.Comparable
```

If I however apply the tx-data directly to the database without serializing and then deserializing it, it just works.

I use:

```clojure
[[org.clojure/clojure "1.10.1"]
 [datascript "0.18.13"]
```

Here's a script to prove my point:

```clojure
(ns datascript-tx-bug.core
  (:require [clojure.edn]
            [datascript.core :as d]))

(def db (d/empty-db))

(def db-tx1
  (d/with
   db
   [{:db/id 1 :test {:something 1}}]))

(def db-tx2
  (d/with
   (:db-after db-tx1)
   [{:db/id 1 :test {:something 2}}]))

(defn combine-txs
  [txs]
  (reduce
   d/db-with
   db
   txs))

(def non-serialized-txs
  [(:tx-data db-tx1)
   (:tx-data db-tx2)])

(def read-db-edn
  (partial clojure.edn/read-string {:readers d/data-readers}))

(def serialized-txs
  [(read-db-edn (pr-str (:tx-data db-tx1)))
   (read-db-edn (pr-str (:tx-data db-tx2)))])

(= serialized-txs non-serialized-txs) ;; true !!

(defn combine-non-serialized []
  (combine-txs non-serialized-txs))
;; Works

(defn combine-serialized []
  (combine-txs serialized-txs))
;; Execution error (ClassCastException) at datascript.db/cmp (db.cljc:317)
;; clojure.lang.PersistentArrayMap cannot be cast to java.lang.Comparable

(type (get-in serialized-txs [0 0 :v])) ;; clojure.lang.PersistentArrayMap

(type (get-in non-serialized-txs [0 0 :v])) ;; clojure.lang.PersistentArrayMap
```

**Comment by fversnel** [comment]
I guess this issue pops up when you try to retract a value which is not the same memory pointer. Datascript then tries to use java.lang.Comparable to determine whether the triple should be retracted, which it can't because a map doesn't implement the java.lang.Comparable interface.

**Comment by tonsky** [comment]
This is very interesting! Although the actual issue here is that `retract` should not compare cardinality one attribute values with cmp (no one should, really). I’ll fix that and maybe will dive deep into what’s going on with deserialization business. Thanks!

**Comment by tonsky** [comment]
This fails too:

```
(require '[datascript.core :as d] :reload-all)
(def db (d/empty-db))
(reduce d/db-with db
  [[[:db/add     1 :test {:something 1}]]
   [[:db/retract 1 :test {:something 1}]
    [:db/add     1 :test {:something 2}]]])
```

As far as I can tell from code, it _should_ fail. The question here is why it doesn’t in the first case.
