### ISSUE TITLE
Failing to unify rule-only variables

### ISSUE THREAD

**Issue by peey** [tonsky/datascript#359]
In the following minimal example:

```
(d/q '[:find ?x
       :in $ %
       :where (constant-rule ?x)]
     '[]
     '[[(constant-rule ?x)
        [3 ?x]]
       ]
     )
```

I expect the result to be `3`, but the returned result is `#{}`.

Is this the intended behaviour or is it a bug?

(PS. This is a minimal example, I had proper data in place of `'[]` earlier, but still I expect this to work as I described)

**Comment by tonsky** [comment]
`[3 ?x]` is just “filter datasource for tuples that has 3 as first element and assign ?x to whatever is second”. If you want to assign 3 to ?x, use ground:

```
[(ground 3) ?x]
```

**Comment by peey** [comment]
Ah that makes sense, thanks. I did not know about `ground`.
