### ISSUE TITLE
feature-request: support for arbitrary query functions (besides built-ins) through an `:allow` list

### ISSUE THREAD

**Issue by peey** [tonsky/datascript#360]
Currently, I believe only functions in https://github.com/tonsky/datascript/blob/master/src/datascript/query.cljc#L194 are allowed to appear in queries.

Would it be possible to have a datomic-like feature for an `:allow` list for whitelisting other custom functions https://docs.datomic.com/cloud/ions/ions-reference.html#ion-config ?

**Comment by peey** [comment]
My bad, it seems like passing any FQNs to datascript in place of a built-in already works!

**Comment by tonsky** [comment]
Yes. And you can also pass any functions as input and then call them:

```
(d/q '[:find ?x
       :in $ ?inc
       :where [?e :attr true]
              [(?inc ?e) ?x]]
  db #(+ % 1))
```
