### ISSUE TITLE
:db.fn/call behavior 

### ISSUE THREAD

**Issue by souenzzo** [tonsky/datascript#366]
On `datomic`, when we call a "transaction function", the `db` that this function receive is the `db` before all transaction

In `datascript 1.0.1`, it receive a "partial db" relative to it's position in transaction

This behavior should be documented ?!

```clojure
(let [conn (ds/create-conn)]
  (ds/transact! conn [[:db.fn/call println]
                      {:a 42}
                      [:db.fn/call println]
                      {:b 24}
                      [:db.fn/call println]]))
=>
#datascript/DB {:schema nil, :datoms []}
#datascript/DB {:schema nil, :datoms [[1 :a 42 536870913]]}
#datascript/DB {:schema nil, :datoms [[1 :a 42 536870913] [2 :b 24 536870913]]}
```

**Comment by tonsky** [comment]
Yes. Are you willing to provide a PR for e.g. README.md?

**Comment by refset** [comment]
Just an FYI that the Datomic Jepsen report discusses this distinuction, and Stu elaborated on the reasoning here: https://news.ycombinator.com/item?id=40373311
