### ISSUE TITLE
how much performance   does :db/type.ref cost while i build a tree type structure

### ISSUE THREAD

**Issue by vlifeng** [tonsky/datascript#368]
Hi    @tonsky 

I have a schema as follows:
`{:id                    {:db/unique :db.unique/identity}
   :content         {}
   :children                {:db/cardinality :db.cardinality/many
                             :db/valueType   :db.type/ref}}`

I apply this  schema to build a tree and id is tree node identity, children is the sub nodes
while i set children to :db/type.ref ,  i have a  20K node tree, i got a 700ms+ avg latency while update content by id using d/transact, but while i  remove the valueType ref, the same transact i got a latency less then 20ms, so, i'd ask if i was make some mistake or this is the real performance?

i was is newest chrome/datascript/18.3

Thank you
lifeng@hulunote

**Comment by tonsky** [comment]
That sounds interesting, but I have no idea what is going on! With :db.type/ref, there’s one more index to update, but that chould slow things down by 1/3, not as much as you described. If you find the cause, I might be fix it

**Comment by vlifeng** [comment]
> That sounds interesting, but I have no idea what is going on! With :db.type/ref, there’s one more index to update, but that chould slow things down by 1/3, not as much as you described. If you find the cause, I might be fix it.
> 
> P.S. One more thing to try is to reference from child to parent, not from parent to child. I am curious how would that perform.

thanks @tonsky and,  I perf It's not a problem of datascript and it's performance is pretty well !
my mistake to apply a whole database search by re-posh subscribe, so as i change some content, that cause  event to search the whole database and update ! so it cause the performance crashed!

Thank you @tonsky .
