### ISSUE TITLE
Here are two cases of ClassCastException

### ISSUE THREAD

**Issue by darkleaf** [tonsky/datascript#369]
jvm 14, clojure 1.10.1, datascipt 1.0.1

# First case

```clojure
(-> (d/empty-db {:attr {:db/cardinality :db.cardinality/many}})
    (d/db-with [[:db/add -1 :attr 1]
                [:db/add -1 :attr "str"]]))
;; BOOM
```

```clojure
(-> (d/empty-db)
    (d/db-with [[:db/add -1 :attr 1]
                [:db/add -2 :attr "str"]]))
;; it's ok
```

It fails with ClassCastException in case of  `db.cardinality/many` but works in case of `db.cardinality/one`.

# Second case

```clojure
(let [db1 (-> (d/empty-db)
              (d/db-with [[:db/add -1 :attr 1]]))
      db2 (-> (d/empty-db)
              (d/db-with [[:db/add -1 :attr "str"]]))]
  (clojure.data/diff db1 db2))

;; BOOM
```

Is PR welcome? :-)

**Comment by tonsky** [comment]
PRs are always welcome! What solution do you have in mind?

There’s an implicit constraint that all of :cardinality/many values will be of the same type, so that they can be compared to each other. This is needed so I have a predictable way to store them in the index. There’s also a problem that you can’t tell in advance if two values would be comparable or not, that’s why the constraint is not enforced.

**Comment by darkleaf** [comment]
I have trouble with the second case. Diff is used by CIDER to make readable test report. And unfortunately, raising the exception hangs my REPL.
So maybe we don't need to fix the first case at all.

**Comment by tonsky** [comment]
If I remember correctly, DS implements some protocols for diff? If that’s the case, we can do try/catch or something like that there.

**Comment by darkleaf** [comment]
I've understood why attributes in different entities don't cause the exception. The AVET index is not used in this case.

```clojure
(-> (ds/empty-db {:attr {:db/index true}}) ;; use AVET index
               (ds/db-with [[:db/add -1 :attr 1]
                            [:db/add -2 :attr "str"]]))

;; BOOM
```

**Comment by darkleaf** [comment]
related to #274, https://github.com/tonsky/datascript/commit/d5c79f5d845e96bc8ec1f9d6f28113492f1a6f40
