### ISSUE TITLE
entity references tempids

### ISSUE THREAD

**Issue by FalseProtagonist** [tonsky/datascript#377]
Hi,

Sorry if this is a stupid question, but from what I understand hammering away on a typescript REPL and reading the unit tests, the below code doesn't work the way one might guess it did if tempids were resolved inside entities, I don't know whether this is intended behaviour or not.

Modifying the test/entity.cljc file:

(deftest test-entity-refs
  (let [db (-> (d/empty-db {:father   {:db/valueType   :db.type/ref}
                            :children {:db/valueType   :db.type/ref
                                       :db/cardinality :db.cardinality/many}})
               (d/db-with
                 [{:db/id -1, :children [-10]}
                  {:db/id -10, :father -1, :children [-100 -101]}
                  {:db/id -100, :father -10}
                  {:db/id -101, :father -10}]))
        e  #(d/entity db %)]
    )))

Hopefully my question makes sense, what I thought might happen:
(temp ids inside entity syntax for transactions get resolved)

What actually happens:
(the temp ids correctly get replaced with positive integers,  but the reference is not "written in" to the referrent, in this query:
q(`[:find ?f ?n :where [?f ":father" ?n]]`, d.db(conn))
one will receive negative numbers as the values, not positive numbers that one might expect.

Why this is relevant:
I'm not understanding the codebase/docs then and I'm not totally stupid
My alternatives that I can see to this syntax are:
individual [db;add] tuple syntax, fine but more verbose
setting db/id to a positive integer, but then I've taken on management of my ids myself

Thanks for this cool project

**Comment by FalseProtagonist** [comment]
Scratch this it was all due to typos it works as expected

**Comment by tonsky** [comment]
Happens to me all the time too :)
