### ISSUE TITLE
How to get a schema correctly?

### ISSUE THREAD

**Issue by darkleaf** [tonsky/datascript#381]
There are two ways to get a schema:

+ `(:schema db)`
+ `(datascript.db/-schema db)`

It seems these are implementation details.
Should we expose a schema via `datascript.core/schema`?
And what about `db/ref?`, `db/reverse-ref?`, `db/multival?`, etc?

**Comment by tonsky** [comment]
`(:schema db)` should be fine?

`db/ref?`, `db/reverse-ref?`, `db/multival?` better stay internal. You can use them if you want, but they might be removed/changed in future versions.

**Comment by tonsky** [comment]
> Should we expose a schema via datascript.core/schema?

But maybe you are right, `:schema` is implementation detail. Seems like a good idea
