### ISSUE TITLE
Hulunote is Roam like product  in China 

### ISSUE THREAD

**Issue by chanshunli** [tonsky/datascript#399]
Hi Nikita 😊，
[Hulunote](https://www.hulunote.com/) is a Roam like product  in China，use the datascript，Can you add to Readme file?  Thanks @tonsky ❤️

Kind Regards,
[Steve Chan](https://twitter.com/hulunote)

**Comment by tonsky** [comment]
Done in https://github.com/tonsky/datascript/commit/3b249ec65dea56b3595c3105675469655d3d2e7d

**Comment by chanshunli** [comment]
Thanks for your help @tonsky ❤️
