### ISSUE TITLE
Comparison predicates do not work for strings

### ISSUE THREAD

**Issue by zoren** [tonsky/datascript#420]
Datomic supports comparisons of strings in predicates like so:
```
[:find ?name
 :where [_ :artist/name ?name]
        [(<= "Q" ?name)]
        [(< ?name "R")]]
```
Should we also support this in datascript?

**Comment by tonsky** [comment]
Oh nice! Yes for sure. PR?

**Comment by zoren** [comment]
Sure I can give it a go. Also comparison should work for ints against strings, etc. I see that’s what Datomic and datahike does.

**Comment by tonsky** [comment]
We already have something like that in `db.clj` called `value-compare`. This function is used to sort attributes in indexes, and attributes can be all sorts of things. I think we should use that.

**Comment by zoren** [comment]
Would it be ok if we only support arity 2 like Datomic does?
