### ISSUE TITLE
Using tupleAttrs from JS throws an error

### ISSUE THREAD

**Issue by alexander-newman-braze** [tonsky/datascript#422]
The following schema throws an error:

```js
datascript.empty_db({
  a: {
    ":db/tupleAttrs": ["b"],
  },
});
```

The stacktrace is:

```
Uncaught TypeError: h.call is not a function
    at db.cljc:690:20
    at tf (core.cljs:2498:22)
    at ac (core.cljs:2548:9)
    at TQ (db.cljc:684:4)
    at UQ (db.cljc:715:36)
    at JQ (db.cljc:780:24)
    at Function.h6.o (js.cljs:79:4)
    at Object.h6 [as empty_db] (js.cljs:78:1)
    at run (test_include_script.html:17:24)
    at test_include_script.html:29:7
```

Specifically the issue appears to be here: https://github.com/tonsky/datascript/blob/9de5f962d0498819de51addb65247907ad99cde5/src/datascript/db.cljc#L690

From what I can tell, `tuple-attr` ends up being a string here rather than a keyword because `schema->clj` doesn’t keywordize the schema’s attributes, so those attributes end up being plain strings in rschema. Updating the previous code to

```js
datascript.empty_db({
  a: {
    ":db/tupleAttrs": [":b"],
  },
});
```

Results in the same error.

**Comment by tonsky** [comment]
Thanks! Fixed in 1.3.7
