### ISSUE TITLE
:db/cas should take a function

### ISSUE THREAD

**Issue by jleonard-r7** [tonsky/datascript#431]
a la [clojure.core/swap!](https://clojuredocs.org/clojure.core/swap!)

It would be trivial to implement and would be vastly more user friendly.

**Comment by tonsky** [comment]
Does :db.fn/call solves it for you?

**Comment by jleonard-r7** [comment]
Ah yes that works. I still think cas is not entirely useful in its current form because one typically wouldn't know the "old-value" without doing a query first.

**Comment by tonsky** [comment]
It might be useful for transactional semantics, I guess. You hold onto value, and when you decide to update it, make sure that nobody has updated it before you

**Comment by jleonard-r7** [comment]
Sure but this is Clojure. STM is something you use, not reinvent/implement for yourself time after time.
