### ISSUE TITLE
equality on ^Entity bypasses db

### ISSUE THREAD

**Issue by dustingetz** [tonsky/datascript#433]
Here: https://github.com/tonsky/datascript/blob/6de343b1b3aecb95c21fbe46384face3f99b989b/src/datascript/impl/entity.cljc#L156

This breaks reactive programming semantics where, when `db` updates, `(d/entity db x)` updates but the result is `=` to the prior result and therefore continuous time reactive engines will skip downstream computation, reusing a buffered prior instance of the entity that is inconsistent with the latest db.

Appears to have been introduced in https://github.com/tonsky/datascript/commit/8264eb0efa500084b24654d1d2f9b69ef1d3f25f , and seems not deeply considered – will you accept a PR uncommenting that check? What needs to be tested?

**Comment by tonsky** [comment]
I don’t remember why we removed db check here. But comparing DBs might be expensive. How about `identical?` here? Would that work for you?

**Comment by tonsky** [comment]
Thanks! Pushed 1.3.14
