### ISSUE TITLE
Can't figure out how to empty database with listeners

### ISSUE THREAD

**Issue by wambat** [tonsky/datascript#45]
Can't figure out how to "clean" database with listeners attached. 
I don't want to go through retract/add on entities, just clean it, and make all listeners jingle.
That's seems not very idiomatic, but how would one practically reset database?
PS great lib, thanks, fills a huge gap for me.

**Comment by cigitia** [comment]
It’ll be wonderful when this gets added. When it does get implemented, it might be best to implement it as a transaction function that can be used in `transact!`, like `:db/add` and `:db.fn/cas`, rather than a function separate from `transact!` that acts directly on connections.

**Comment by tonsky** [comment]
@cigitia yep, sounds reasonable

**Comment by tonsky** [comment]
Just added `reset-conn!` function to reset database value inside a conn and trigger all listeners. Usage example: https://github.com/tonsky/datascript/blob/master/test/datascript/test/conn.cljc

@cigitia I would pass on your idea for now, if you need that kind of function inside a transaction it’s not that hard to build for youself. Transactions totally support user-provided functions
