### ISSUE TITLE
Upsert of datom with composite tuple containing lookup ref fails

### ISSUE THREAD

**Issue by telekid** [tonsky/datascript#450]
I believe this is related to https://github.com/tonsky/datascript/issues/378, to possibly not the exact same issue.

In the following example, I would expect the second transaction to resolve the second entity to an existing datom via the `:a+b` tuple (resulting in an upsert, though really a noop in this case.)

```clojure
(deftest test-upsert
  (let [conn (d/create-conn {:x-ref {:db/unique :db.unique/identity}
                             :a {:db/valueType :db.type/ref}
                             :a+b {:db/valueType :db.type/tuple
                                   :db/tupleAttrs [:a :b]
                                   :db/unique :db.unique/identity}})]

    (d/transact!
     conn
     [{:db/id "x"
       :x-ref 1}
      {:a "x"
       :b 2}])

    (is (= #{[1 :x-ref 1]
             [2 :a 1]
             [2 :a+b [1 2]]
             [2 :b 2]}
           (tdc/all-datoms (d/db conn))))

    (d/transact!
     conn
     [{:db/id "x"
       :x-ref 1}
      {:a "x"
       :b 2
       :foo :bar}]) ;; upsert 2, associating :bar to :foo

    (is (= #{[1 :x-ref 1]
             [2 :a 1]
             [2 :a+b [1 2]]
             [2 :b 2]}
             [2 :foo :bar]

           (tdc/all-datoms (d/db conn))))))
```

However, it fails with the following exception:

```
1. Unhandled clojure.lang.ExceptionInfo
   Cannot add #datascript/Datom [3 :a+b [1 2] 536870914 true] because of unique
   constraint: (#datascript/Datom [2 :a+b [1 2] 536870913 true])
   {:error :transact/unique,
    :attribute :a+b,
    :datom #datascript/Datom [3 :a+b [1 2] 536870914 true]}
...
```

Are my expectations wrong here?

**Comment by tonsky** [comment]
Looks to me like it should work, yes

**Comment by telekid** [comment]
Awesome. I haven't poked my head into DataScript's internals before, but I'll do a bit of digging and see if I can figure out what's going on.

**Comment by telekid** [comment]
Finally got around to looking into this.

I believe what is happening is that [`resolve-upserts`](https://github.com/tonsky/datascript/blob/420fec9bd2f267d113c7111fc6b736bf0410d3ae/src/datascript/db.cljc#L1252) isn't 
accounting for the possibility of upserting via tuple containing a tempid; this causes [`some? upserted-eid`](https://github.com/tonsky/datascript/blob/420fec9bd2f267d113c7111fc6b736bf0410d3ae/src/datascript/db.cljc#L1524) to return `nil`, resulting in a new eid being generated [here](https://github.com/tonsky/datascript/blob/420fec9bd2f267d113c7111fc6b736bf0410d3ae/src/datascript/db.cljc#L1539). The presence of this new entity is what causes the unique constraint violation to fail.

My guess is that you may want to move the [`retry-with-tempid`](https://github.com/tonsky/datascript/blob/420fec9bd2f267d113c7111fc6b736bf0410d3ae/src/datascript/db.cljc#L1525-L1528) logic into `resolve-upserts`, and then update that function to handle tuples + tempids.

Does that seem right?

**Comment by telekid** [comment]
After a night's rest, I came up with a different approach. Rather than using tempids as a method of resolving existing entities, leverage lookup refs. [This is more idiomatic.](https://blog.datomic.com/2014/02/datomic-lookup-refs.html#:~:text=Lookup%20refs%20can%20also%20be%20used%20to%20refer%20to%20existing%20entities%20in%20transaction%20data.%20%C2%A0This%20allows%20updating%20transactions%20to%20specify%20%3Adb/id%20directly%20instead%20of%20using%20a%20dummy%20upsert%2C%20as%20shown%20below%3A)

```clojure
(deftest upsert'
  (let [conn (d/create-conn {:x-ref {:db/unique :db.unique/identity}
                             :a {:db/valueType :db.type/ref
                                 :db/unique :db.unique/identity}
                             :a+b {:db/valueType :db.type/tuple
                                   :db/tupleAttrs [:a :b]
                                   :db/unique :db.unique/identity}})]

    (d/transact!
     conn
     [{:x-ref 1}
      {:a [:x-ref 1]
       :b 2}])

    (is (= #{[1 :x-ref 1]
             [2 :a 1]
             [2 :b 2]
             [2 :a+b [1 2]]}
           (tdc/all-datoms (d/db conn))))

    (d/transact!
     conn
     [{:a [:x-ref 1]
       :b 2
       :foo :bar}])

    (is (= #{[1 :x-ref 1]
             [2 :a 1]
             [2 :a+b [1 2]]
             [2 :b 2]
             [2 :foo :bar]}

           (tdc/all-datoms (d/db conn))))))

**Comment by tonsky** [comment]
Oh! I didn’t even noticed that :a was a ref. Yeah lookup refs are probably better here
