### ISSUE TITLE
do we have double vector type?

### ISSUE THREAD

**Issue by usametov** [tonsky/datascript#454]
Hi, 
Assuming that I want to add vector search capability to Datascript. 
How can I specify double array type in a schema?
To clarify, I do not want a bunch of triples with double values, I just want one triple holding one value -- double array. Is it possible?

**Comment by tonsky** [comment]
You can just add vectors as values, this doesn’t need to be specified in schema

**Comment by usametov** [comment]
cool, thanks :)
