### ISSUE TITLE
Regression in 1.6.4: unbound vars not filtered

### ISSUE THREAD

**Issue by mainej** [tonsky/datascript#469]
While drafting #468, I noticed another regression. The two problems are quite likely related, but I'm submitting this one separately so I can explain it in isolation.

Consider the same query as in #468, but with the following edit to the or-join:

```diff
(or-join
 [?x ?y]
 (and [?x :parent ?z]
      [?z :parent ?y])
- [?y :parent ?x])
+ [?x :parent ?y])
```

In 1.6.3 this produces:

```clojure
(["alice" #{[1 3] [1 2]}] 
 ["bob" #{[2 3]}]
 ["clara" #{}])
```

In 1.6.4 it produces:

```clojure
(["alice" #{[1 3] [1 2]}]
 ["bob" #{[2 3]}] 
 ["clara" #{[3 nil]}])
```

It's very surprising to see a `nil` in the output of a query!
* ❌ When the query is run for "clara", neither part of the `or-join` binds `?y`. In 1.6.3 this would remove all tuples, but it seems that now `?y` is bound to `nil`.

**Comment by tonsky** [comment]
Hopefully fixed in 1.6.5
