### ISSUE TITLE
Transacting many ref value as set of inline maps

### ISSUE THREAD

**Issue by aiba** [tonsky/datascript#476]
This worked in 1.6.5:

```clojure
(require '[datascript.core :as d])

(def schema {:item/tags {:db/valueType :db.type/ref
                         :db/cardinality :db.cardinality/many}})

(def conn (d/create-conn schema))

(d/transact! conn [{:db/id "1"
                    :item/tags #{{:tag/name "foo"}
                                 {:tag/name "bar"}}}])
```

In 1.7.1, it throws an error, `"Expected number or lookup ref for entity id, got nil"`.

I tracked it to the new function, `assoc-auto-tempids`, which only assigns tempids to inline maps of a many ref value if the value is `sequential?`, which sets are not.  So now one must use a sequential value, such as:

```clojure
(d/transact! conn [{:db/id "1"
                    ;; Vector, not set.
                    :item/tags [{:tag/name "foo"}
                                {:tag/name "bar"}]}])
```

But I think it's logical to be able to transact many ref entities inline as a set of maps, since that's also how they are returned when queried.

Is this as simple as changing [This line](https://github.com/tonsky/datascript/blob/0fd30aa85942d6472fce07c94e124697639a2363/src/datascript/db.cljc#L1307) to check `coll?` rather than `sequential?`?

**Comment by tonsky** [comment]
Yeah sorry about that. Try 1.7.2

**Comment by aiba** [comment]
Working great in 1.7.2, thank you so much!
