### ISSUE TITLE
validate :db/id keys to ensure only integers are used

### ISSUE THREAD

**Issue by jumblerg** [tonsky/datascript#48]
```clojure

(def db (atom (d/empty-db)))

(def data
 [ {:city/name           "New York City"
    :city/location       "New York"
    :city/image          "/img/home/NewYorkCity.jpg" }
   {:city/name           "Rio de Janerio"
    :city/location       "Brazil"
    :city/image          "/img/home/RioDeJaneiro.jpg" }
   {:city/name           "Auckland"
    :city/location       "New Zealand"
    :city/image          "/img/home/Auckland.jpg" }
   {:city/name           "Berlin"
    :city/location       "Germany"
    :city/image          "/img/home/Berlin.jpg" }
   {:city/name           "Amsterdam"
    :city/location       "Netherlands"
    :city/image          "/img/home/Amsterdam.jpg" }
   {:city/name           "Paris"
    :city/location       "France"
    :city/image          "/img/home/Paris.jpg" }])

(swap! db d/db-with data)

 (d/q '[:find ?e :where [?e :city/name]] @db)
;; #{[2]}
```
however, when the namespace is removed, it returns the correct number.

**Comment by jumblerg** [comment]
this query works, however, when i drop the city namespace from the name attribute.  i've also noticed that namespaces don't seem to be used with any of the attributes in the unit tests (beyond those specific to the database).

**Comment by tonsky** [comment]
Sorry, I don’t understand what the issue is. I get `#{[5] [3] [4] [1] [6] [2]}` as a result, which seems ok.

Namespaces have no special meaning in DataScript. `:name` and `:city/name` are two completely different keywords.

**Comment by jumblerg** [comment]
when i use :name it returns as you described, but when i qualify an attribute with a namespace (e.g. :city/name), the same query only returns a single result.

i'm happy to test this further to narrow down the problem if you're unable to reproduce the case i provided

**Comment by tonsky** [comment]
The snippet you’ve provided, if I execute it literally, as is, it returns `#{[5] [3] [4] [1] [6] [2]}`, at least for me. Please help me to reproduce what you’ve experienced

**Comment by jumblerg** [comment]
apologies, i left something out of the case i provided you earlier

```clojure
(def db (atom (d/empty-db)))

(swap! db d/db-with
  [
   {:db/id               :some/ident
    :entity/label        "Details"
    :entity/children     [1 2 3] }

   {:city/name           "New York City"
    :city/location       "New York"
    :city/image          "/img/home/NewYorkCity.jpg" }
   {:city/name           "Rio de Janerio"
    :city/location       "Brazil"
    :city/image          "/img/home/RioDeJaneiro.jpg" }
   {:city/name           "Auckland"
    :city/location       "New Zealand"
    :city/image          "/img/home/Auckland.jpg" }
   {:city/name           "Berlin"
    :city/location       "Germany"
    :city/image          "/img/home/Berlin.jpg" }
   {:city/name           "Amsterdam"
    :city/location       "Netherlands"
    :city/image          "/img/home/Amsterdam.jpg" }
   {:city/name           "Paris"
    :city/location       "France"
    :city/image          "/img/home/Paris.jpg" } 
   {:hostel/name         "My Hostel"} ])

(print :city-ids (d/q '[:find ?e :where [?e :city/name]] @db))

;; :city-ids #{[5] [4] [2]}
```
* removing :entity/label on the first entity produces the expected result
* substituting the vector on entity children with a string produces the expected result
* removing :entity/children on the first entity produces the expected result
* removing the first entity entirely produces the expected result
* adding another entity like the first one causes only one result to be returned by the query as i submitted earlier

**Comment by jumblerg** [comment]
my datalog queries continue to fall on entities of all varieties, but i continue to observe the trend that, when i drop the namespace qualifier, they succeed afterwards.

**Comment by tonsky** [comment]
Problem is with you using keyword for `:db/id` instead of number. This leads to these strange behaviours you observe. I don’t have validation here (yet), but you can’t do that. Entity ids are always integers. I will reopen this issue to add `:db/id` validation in the next version.

**Comment by jumblerg** [comment]
ah - many thanks! i was confused by your discussion of idents in the documentation.  i understand datomic wouldn't permit a non-interger in the :db/id position, but got the impression that was somehow supported here.  since the ids deviate from the datomic specification,  it would be helpful to have a sample transaction in the map/entity format like https://github.com/Datomic/day-of-datomic/blob/master/resources/day-of-datomic/social-news.edn.

**Comment by jumblerg** [comment]
just wanted to let you know that everything works great now; the terrifying non-deterministic queries have gone away entirely. could you push a 0.7.3 jar when it's convenient with the corrected (d/entity db nil) behavior i submitted on the the previous ticket?

thanks again!

**Comment by tonsky** [comment]
@jumblerg just pushed 0.8.0
