### ISSUE TITLE
`sum` dedupes inputs

### ISSUE THREAD

**Issue by filipesilva** [tonsky/datascript#480]
When using `sum`, equal inputs are removed before being aggregated:

```clj
(require '[datascript.core :as d])

(d/q '[:find  (sum ?x)
       :where [?e :has ?x]]
     [[1 :has 3]
      [2 :has 3]
      [3 :has 2]])

;; => ([5])
```

**Comment by tonsky** [comment]
Yes. This is a counter-intuitive behavior carried on from Datomic. You need to add `:with` so that duplicates will not be removed https://docs.datomic.com/query/query-data-reference.html#with

**Comment by filipesilva** [comment]
And thus, I was enlightened 🙏
