### ISSUE TITLE
Lookup ref as literal in query fails

### ISSUE THREAD

**Issue by sparkofreason** [tonsky/datascript#53]
This query works:
```clojure
(d/q '[:find ?e :in $ ?et :where [?e :entity/type ?et]] db [:db/ident :entity.type/survey])
```

This one returns an empty result:
```clojure
(d/q '[:find ?e :where [?e :entity/type [:db/ident :entity.type/survey]]] db)
```

**Comment by tonsky** [comment]
Yep. It came from limitation of Datomic, found [here](http://docs.datomic.com/identity.html#sec-7):

> Lookup refs cannot be used in the body of a query though they can be used as inputs in a parameterized query.

I believe it’s an implementation detail of their query parser which cannot tell the difference between function call, predicate and lookup ref (they all use list/vector form as a distinguisher).

I’ll look into it, it seems like most of the time we can tell the difference though. So I don’t see why DS shouldn’t allow this kind of syntax. Thanks for pointing that out!

**Comment by sparkofreason** [comment]
Thanks for the link. Seems like they should be able to support that, at least in value position. Two main use-cases were to bridge the lack of :db/ident support, and allow sharing of the same queries between Datomic and Datascript. The latter is moot, and the former is really it's own issue, so closing this.
