### ISSUE TITLE
Infinite loop when using pull API on circular component reference

### ISSUE THREAD

**Issue by cigitia** [tonsky/datascript#58]
In DataScript 0.9.0, as far as I can tell, the `pull` function may lock the program in an infinite loop if it is used on an entity whose component attribute refers to itself, in a circular reference.

A demonstration script is at
https://gist.github.com/cigitia/c1f1fc48ebc041c979c5.
Line 24 needs to be uncommented to freeze the program.

This especially may happen when creating components in the same transaction as their parents, due to current behavior in the generation of component entities’ IDs; see #59.

DataScript is amazing; thank you for creating it.

**Comment by tonsky** [comment]
Will take a look at this a little bit later. If I remember correctly, components fetch is unconditional, so if they are in a cycle, it’s an infinite loop. Datomic hangs on this too. Idea is to not put your components in a cycle. Probably there’s no reason to emulate that behaviour of Datomic here.

**Comment by cigitia** [comment]
Thanks for considering it; if Datomic also freezes on this, thinking more about whether to check for this is understandable. There are three options that I can think of:

* Leave the infinite-loop behavior completely in; no checks at all.
* Use `assert` to check for infinite loops to throw errors before they occur; can be enabled or disabled for different compiler builds using the [`:elide-asserts` option](https://github.com/clojure/clojurescript/wiki/Compiler-Options#elide-asserts); leaves in infinite loops only on optimized builds for which `:elide-asserts` is `true`.
* Check for infinite loops and terminate them, causing circular references to be resolved without throwing errors or infinitely realizing more objects.

In addition, the touch API probably also suffers from this same problem since, when used on an entity, it recursively realizes its components too; I haven't yet tested this, though.

**Comment by tonsky** [comment]
I think there’s no reason for allowing infinite recursion for components. I guess Datomic does that is a bug. So we’ll fix that eventually, @dthume maybe you can take a look?

**Comment by tonsky** [comment]
Fixed in #61 and #62
