### ISSUE TITLE
Case of infinite ref recursion in Pull API

### ISSUE THREAD

**Issue by tonsky** [tonsky/datascript#62]
This hangs:

    (deftest test-recursion
      (let [empty (d/empty-db {:part { :db/valueType :db.type/ref }
                               :spec { :db/valueType :db.type/ref }})]
        (let [db (d/db-with empty [[:db/add 1 :part 2]
                                   [:db/add 2 :part 3]
                                   [:db/add 3 :part 1]
                                   [:db/add 1 :spec 2]
                                   [:db/add 2 :spec 1]])]
          (is (= (d/pull db '[:db/id {:part ...} {:spec ...}] 1)
                 {:db/id 1,
                  :spec {:db/id 2
                         :spec {:db/id 1, :spec {:db/id 2}, :part {:db/id 2}}
                         :part {:db/id 3, :part {:db/id 1, :spec {:db/id 2}, :part {:db/id 2}}}}
                  :part {:db/id 2
                         :spec {:db/id 1, :spec {:db/id 2}, :part {:db/id 2}}
                         :part {:db/id 3, :part {:db/id 1, :spec {:db/id 2}, :part {:db/id 2}}}}}))))

I believe it’s related to the way how different recursion branches are handled. When inside single branch, they should share “seen” set, so sequence of unwraps like :part → :spec → :part → :spec will eventually end on a seen entity no matter what actual path to it was.

Also when writing this I noticed that recursion is handled a little bit different than in Datomic:

    (let [db (d/db-with empty [[:db/add 1 :part 1]])]
      (is (= (d/pull db '[:db/id {:part ...}] 1)
             {:db/id 1, :part {:db/id 1, :part {:db/id 1}}})))

From what I can tell, in Datomic, initial entity from where recursion starts is not considered as _seen_, that’s because when we see `:part {:db/id 1}` first time we try to expand that. When we see it second time, it’s now _seen_, and second expansion does not happen.

@dthume hope you don’t mind me assigning you to this?

**Comment by tonsky** [comment]
@dthume I added you to collaborators, so you can create branches in this repo instead of in a fork if you wish. It’s actually will be slightly easier to me to handle them this way

**Comment by tonsky** [comment]
Also I think recursion in components and in refs should work more or less the same, ideally via the same algorithm. And they should share this “seen refs” stack for sure

**Comment by dthume** [comment]
No problem; I'd actually noticed the difference from datomic when working through #58, and was planning to raise a separate issue about it.

**Comment by dthume** [comment]
I've pushed to the [issue-62](https://github.com/tonsky/datascript/tree/issue-62) branch, if you'd like to review the changes. It seems to bring datascript in line with datomic, and fix the infinite loop.

**Comment by tonsky** [comment]
Amazing! Thanks, merged to master
