### ISSUE TITLE
evicting data

### ISSUE THREAD

**Issue by uwo** [tonsky/datascript#64]
Could anyone recommend how I might approach evicting data, perhaps in an LRU style?  I display a lot of time series data that I assume will eventually blow up if I store it all.  Thanks for datascript, tonksy!

**Comment by tonsky** [comment]
Just run a periodic task to clean up the data. Simple [:db/retract eid attr
value] (or maybe [:db.fn/retractEntity eid] as it’s simpler to use) will do.

DataScript does not store history, so if you retract a datom, it’ll be
removed from DB completely. This way DS can work in a fixed memory
footprint.

**Comment by uwo** [comment]
Ah! I didn't read the retract source closely enough. Next time I"ll try to put questions like this in Gitter.

Thanks!
