### ISSUE TITLE
v0.10.0: Circular reference when generating ID of new component entity within transaction

### ISSUE THREAD

**Issue by cigitia** [tonsky/datascript#66]
Related to #59. In DataScript 0.10.0, creating component entities by nesting maps in a transaction can still cause circular references, under certain circumstances when the new parent entity has an explicit ID but its first component entity has an implicit ID.

A demonstration script with two ways to produce the circular-reference behavior is at <https://gist.github.com/cigitia/106e95c3824783442c5b>.

Thanks a ton again for DataScript.

**Comment by cigitia** [comment]
Just tested again in DataScript 0.11.1; the circular references still occur.

**Comment by tonsky** [comment]
Sorry it took so long :)

**Comment by cigitia** [comment]
Thank you super much! DataScript is amazing!
