### ISSUE TITLE
Strange error when using vector as datom's value

### ISSUE THREAD

**Issue by myguidingstar** [tonsky/datascript#69]
```clj
(let [conn (d/create-conn {})]
    (d/transact! conn
                 [{:key [:value 2]}
                  {:key [:value "foo"]}]))
;; => clojure.lang.ExceptionInfo: #<Error: compare on non-nil objects of different types>
```

**Comment by tonsky** [comment]
It’s because values should be comparable:

**Comment by myguidingstar** [comment]
What's the point of that guard? To prevent duplicated k/v pairs? Then value of different types should be valid, too.

Actually I used similar code to store some rum/sablono templates (as clojurescript vectors) to datascript. Now I have to wrap the template in a list as a workaround.

The problem is values of different entities are checked with `compare`, too?
```clj
(let [conn (d/create-conn {})]
  (d/transact! conn
               [{:db/id -1 :key [:value 2]}
                {:db/id -2 :key [:value "foo"]}]))
;; => exception again
```

**Comment by tonsky** [comment]
It’s useful to have total order of all values of all types. I don’t know why it is in CLJS, unfortunately. It gets even funnier: you cannot compare array-map with hash-map for example :)

**Comment by myguidingstar** [comment]
haha, thanks. Turns out that wrapping things in lists is the way to compare them all
```
(compare (list (array-map :a 1 :b 2))
         (list (hash-map :a 1 :b 2)))
;; => -1
```

**Comment by myguidingstar** [comment]
Reported as Clojurescript bug instead
http://dev.clojure.org/jira/browse/CLJS-1200

**Comment by tonsky** [comment]
I’m not sure what the right solution to this problem is. Clojure does work the same way:

```
(compare [1 "a"] [1 :key])
=> java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.lang.String
```

Fix to this might be a language design-level decision.

In Datomic you can put only basic types to values. Maybe we can think of something for DataScript too. I don’t want to give up ability to store any values. Maybe “not-comparable” schema attribute. I’ll think about it.

**Comment by sonwh98** [comment]
I am running into this problem trying to store javascript objects. anyway around this?

**Comment by tonsky** [comment]
@sonwh98 nope, you have to define IComparable for the objects you’re storing. Or put them in a wrapper that does define that.

**Comment by sonwh98** [comment]
I am trying to store functions. When I tried to extend IFn to impelment IComparable, it doesn't seem to work 

``` (extend-protocol IComparable
                 FamousBox (^number -compare [x y]
                                             (famous-compare x y))
                 Vec3 (^number -compare [x y]
                                        (famous-compare x y))
                 Quaternion (^number -compare [x y]
                                              (famous-compare x y))
                 Spring (^number -compare [x y]
                                          (famous-compare x y))
                 RotationalSpring (^number -compare [x y]
                                                    (famous-compare x y))
                 Node (^number -compare [x y]
                                        (famous-compare x y))
                 IFn (^number -compare [x y]
                                       (println "compare functions x=" x " y=" y)
                                       (= x y))
                 )
```
The other types work but not IFn. The println statement is never reached. Any idea what I am doing wrong?  The type of javascript functions is cljs.core.IFn right?

**Comment by tonsky** [comment]
Try `(cond (identical? x y) 0 (< x y) -1 :else 1)` as an implementation

**Comment by sonwh98** [comment]
Thanks @tonsky . For the benefit of others who might be running into the same problem. IFn  can't be extended because its a protocol.

The solution is to extend function. 
```
(extend-protocol IComparable
    function (^number -compare [x y]
                                       (println "compare functions x=" x " y=" y)
                                       (your-compare-function x y))
```

**Comment by tonsky** [comment]
Ok guys, I now has a real solution for this. Read [the changelog](https://github.com/tonsky/datascript/blob/master/CHANGELOG.md) for 0.12.0 version. Thanks for waiting! // cc @sonwh98 @myguidingstar

**Comment by tonsky** [comment]
@carocad not currently. I’ll probably do this https://github.com/tonsky/datascript/issues/274 at some point in the future, that should solve it for Clojure. Consider using something else for a key for now (e.g. string representation of what you currently have there?)

**Comment by carocad** [comment]
@tonsky fair enough. Thanks for the support. For the time being I am just "hoping" that the users won't do that since it is quite weird to use numbers in some cases but strings on others. 

So if it happens then I just show that error. Btw, I saw that the Clojure comparators page now has an entry on cross type comparators, maybe you could use some of that code. 

Hope it helps

https://clojure.org/guides/comparators
