### ISSUE TITLE
d.init_db with schema from Javascript

### ISSUE THREAD

**Issue by motosota** [tonsky/datascript#73]
Hi,

I'm struggling to use d.init_db and create a schema at the same time like so:

d.init_db([[1, "name", "Ivan"],[1, "age", 17],[2, "name", "Igor"],[2, "age", 35][1, "friend", 2]], [{"friend": {":db/valueType": ":db.type/ref"}}]);

Gives 
Error: nth not supported on this type function Object() { [native code] }

What am I doing wrong?

Mike

**Comment by tonsky** [comment]
It’s a bug in DS and also you shouldn’t wrap schema in Array. Correct code should be:
```
d.init_db([[1, "name", "Ivan"],
            [1, "age", 17],
            [2, "name", "Igor"],
            [2, "age", 35],
            [1, "friend", 2]],
  {"friend": {":db/valueType": ":db.type/ref"}});
```

**Comment by tonsky** [comment]
@motosota just pushed new release for you https://github.com/tonsky/datascript/releases/tag/0.11.0
