### ISSUE TITLE
pull api: wildcard is not compatible with reverse refs

### ISSUE THREAD

**Issue by tonsky** [tonsky/datascript#80]
If we have wildcard and something else in a pull spec, something else should be merged on top of wildcard pull:

```
(deftest test-pull-wildcard
  (is (= {:db/id 2 :name "David" :_child [{:db/id 1}]}
         (d/pull test-db '[* :_child] 2))))
```

```
FAIL in (datascript.test.pull-api/test-pull-wildcard) (:)
expected: (= {:db/id 2, :name "David", :_child [{:db/id 1}]} (d/pull test-db (quote [* :_child]) 2))
  actual: (not (= {:db/id 2, :name "David", :_child [{:db/id 1}]} {:db/id 2, :name "David"}))
```

**Comment by tonsky** [comment]
@dthume fancy take a look?

**Comment by dthume** [comment]
Sure!

**Comment by dthume** [comment]
Fix for the given test case pushed to: [issue-80](https://github.com/tonsky/datascript/tree/issue-80); I can't see any outstanding problems with it so, assuming you agree, I think it's safe to merge.

**Comment by dthume** [comment]
Gah apologies, didn't mean to jump the gun and close it :-)

**Comment by tonsky** [comment]
Awesome! Thanks a lot!
