### ISSUE TITLE
not able to use datascript version 0.11.2

### ISSUE THREAD

**Issue by ThomasDeutsch** [tonsky/datascript#84]
I get this error when i compile my project with datascript 0.11.2:

```
clojure.lang.ExceptionInfo: Could not locate datascript/core__init.class or data
script/core.clj on classpath:  at line 1 file:/C:/Users/deutsch/.m2/repository/d
atascript/datascript/0.11.2/datascript-0.11.2.jar!/datascript/core.cljc {:tag :c
ljs/analysis-error, :file "file:/C:/Users/deutsch/.m2/repository/datascript/data
script/0.11.2/datascript-0.11.2.jar!/datascript/core.cljc", :line 1, :column 1}
```

datascript-version: 0.11.1 works fine for me.
i use [org.clojure/clojurescript "0.0-3211"].

**Comment by tonsky** [comment]
Which version of Clojure are you at? Must be 1.7.0-beta2 or later (latest
ATM is 1.7.0-RC1)

**Comment by ThomasDeutsch** [comment]
Thank you for your quick reply. 
I was on clojure 1.6.0  -  i changed to 1.7.0-beta2  and it is working now.
