### ISSUE TITLE
how to store special string characters �

### ISSUE THREAD

**Issue by ThomasDeutsch** [tonsky/datascript#85]
How can i store special characters in datascript? ( i have Umlaute like "Straße" or "Strähnen" ).
When i read the strings that contain special characters, they are replaced by: �

**Comment by tonsky** [comment]
Are you sure it’s related to DataScript? I do not modify strings in any way. Maybe it’s CLJS issue?

**Comment by ThomasDeutsch** [comment]
For one single file in my project - the editor choosed to set the encoding to ANSI - instead of UTF-8. :(  Thank you again for your quick response.
