### ISSUE TITLE
How-To:  to change an entity-id

### ISSUE THREAD

**Issue by ThomasDeutsch** [tonsky/datascript#88]
For an input-form, i save all data in entity with :db/id 1.
Before the form gets displayed, i load all form-data into this entity.

From this point, the entity-nr 1 will represent the form data.

When the user clicks "apply", i would like to make a duplicate of entity 1 or change the :db/id to another value. 

i imagine the solution to be like this, but it will only retract entity 1.

```clj
(defn save-customer [customer]
  (let [new-customer (assoc (into {} (d/touch customer)) :db/id -1 )]
    (d/transact! conn [new-customer
                       [:db.fn/retractEntity 1]])))
```

**Comment by tonsky** [comment]
It should work. Another way to get entity data is `(d/pull db eid '[*])`. Also you’ll probably need special handling for references.

**Comment by ThomasDeutsch** [comment]
You are right, it should have worked, but in my case - one of the attributes was a 
```
{:db/unique :db.unique/identity}
```
so i needed to delete the form entity first, before i could make the transaction.
Nice, that datascript prevented this mistake, but i got no error.

**Comment by tonsky** [comment]
Very strange — usually DS throws on identity violations. I’ll check into it

**Comment by ThomasDeutsch** [comment]
when you look at the save-customer example -
i get an error when i use a :db/id that is > 0 in that transaction - not so if i use a negative :db/id
