### ISSUE TITLE
"not" in where clause is highly requested :)

### ISSUE THREAD

**Issue by mprokopov** [tonsky/datascript#90]
As far as I saw in "datjscript-todo" example application, there were construction something like manual intersection between "all" data and "not-to-be-in-dataset" data.

So support for "not" query functionality would be great!

And many thanks for great datascript library. That's something really new and demanded for contemporary web development.

**Comment by narma** [comment]
I think it related to this issue https://github.com/tonsky/datascript/issues/50

**Comment by tonsky** [comment]
Yep, I’ll close this as a dup for #50. I’m working on it
