### ISSUE TITLE
add optional time to squuid constructor

### ISSUE THREAD

**Issue by ThomasDeutsch** [tonsky/datascript#95]
I would love to have the option to pass a optional timestamp to the squuid constructor.

one example scenario:
I store all entities in firebase. For every entity, the key is the squuid from datascript. The value is a transit-string.
If every squuid would contain the due-date of that item ( not the creation-time ) - the backend server will be able to detect all the items with that due-date without the need to transit every value. This would be perfect for many cron-jobs.

This is my Server-DB architecture:
![](https://www.firebase.com/resources/images/blog/client_server.png)

**Comment by tonsky** [comment]
Care to provide a PR? It should be trivial

**Comment by ThomasDeutsch** [comment]
[pull request] (https://github.com/tonsky/datascript/pull/96)

**Comment by ThomasDeutsch** [comment]
https://github.com/tonsky/datascript/pull/97

**Comment by tonsky** [comment]
Decided to go with my own patch — yours has a bug, it was faster to fix it by myself: https://github.com/tonsky/datascript/commit/f2f05fa7ef956358ef5680e861b11a6e84087be3

Note that only seconds, not milliseconds, go to squuid (so they fit into 32 bit). Also note that the purpose of squuid was to provide monotonic unique decentralized identities. The fact that they’re using time is just a coincidence. It would be reasonable not to rely on that, and store timestamp explicitly. I’m adding sqquid/1 mostly for the symmetry of the API.

**Comment by ThomasDeutsch** [comment]
Thank you very mutch. Sorry about not getting it right.

2015-07-19 15:03 GMT+02:00 Nikita Prokopov <notifications@github.com>:
